
var Module = (function() {
  var _scriptDir = typeof document !== 'undefined' && document.currentScript ? document.currentScript.src : undefined;
  if (typeof __filename !== 'undefined') _scriptDir = _scriptDir || __filename;
  return (
function(Module) {
  Module = Module || {};


var h;h||(h=typeof Module !== 'undefined' ? Module : {});var aa,ba;h.ready=new Promise(function(a,b){aa=a;ba=b});var ca={},n;for(n in h)h.hasOwnProperty(n)&&(ca[n]=h[n]);var da="./this.program",ea=!1,v=!1,fa=!1,ja=!1;ea="object"===typeof window;v="function"===typeof importScripts;fa="object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node;ja=!ea&&!fa&&!v;var y="",ka,la,ma,na,oa;
if(fa)y=v?require("path").dirname(y)+"/":__dirname+"/",ka=function(a,b){na||(na=require("fs"));oa||(oa=require("path"));a=oa.normalize(a);return na.readFileSync(a,b?null:"utf8")},ma=function(a){a=ka(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a},1<process.argv.length&&(da=process.argv[1].replace(/\\/g,"/")),process.argv.slice(2),process.on("uncaughtException",function(a){throw a;}),process.on("unhandledRejection",z),h.inspect=function(){return"[Emscripten Module object]"};else if(ja)"undefined"!=
typeof read&&(ka=function(a){return read(a)}),ma=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");assert("object"===typeof a);return a},"undefined"!==typeof print&&("undefined"===typeof console&&(console={}),console.log=print,console.warn=console.error="undefined"!==typeof printErr?printErr:print);else if(ea||v)v?y=self.location.href:"undefined"!==typeof document&&document.currentScript&&(y=document.currentScript.src),_scriptDir&&(y=_scriptDir),
0!==y.indexOf("blob:")?y=y.substr(0,y.lastIndexOf("/")+1):y="",ka=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},v&&(ma=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),la=function(a,b,c){var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=function(){200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)};
var pa=h.print||console.log.bind(console),B=h.printErr||console.warn.bind(console);for(n in ca)ca.hasOwnProperty(n)&&(h[n]=ca[n]);ca=null;h.thisProgram&&(da=h.thisProgram);var qa;h.wasmBinary&&(qa=h.wasmBinary);var noExitRuntime=h.noExitRuntime||!0;"object"!==typeof WebAssembly&&z("no native wasm support detected");var ra,sa=!1;function assert(a,b){a||z("Assertion failed: "+b)}var ta="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function C(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.subarray&&ta)return ta.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|f);else{var k=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|k:(e&7)<<18|f<<12|k<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d}
function ua(a,b,c,d){if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var k=a.charCodeAt(f);if(55296<=k&&57343>=k){var l=a.charCodeAt(++f);k=65536+((k&1023)<<10)|l&1023}if(127>=k){if(c>=d)break;b[c++]=k}else{if(2047>=k){if(c+1>=d)break;b[c++]=192|k>>6}else{if(65535>=k){if(c+2>=d)break;b[c++]=224|k>>12}else{if(c+3>=d)break;b[c++]=240|k>>18;b[c++]=128|k>>12&63}b[c++]=128|k>>6&63}b[c++]=128|k&63}}b[c]=0;return c-e}
function va(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}var wa="undefined"!==typeof TextDecoder?new TextDecoder("utf-16le"):void 0;function xa(a,b){var c=a>>1;for(var d=c+b/2;!(c>=d)&&ya[c];)++c;c<<=1;if(32<c-a&&wa)return wa.decode(D.subarray(a,c));c="";for(d=0;!(d>=b/2);++d){var e=F[a+2*d>>1];if(0==e)break;c+=String.fromCharCode(e)}return c}
function za(a,b,c){void 0===c&&(c=2147483647);if(2>c)return 0;c-=2;var d=b;c=c<2*a.length?c/2:a.length;for(var e=0;e<c;++e)F[b>>1]=a.charCodeAt(e),b+=2;F[b>>1]=0;return b-d}function Aa(a){return 2*a.length}function Ba(a,b){for(var c=0,d="";!(c>=b/4);){var e=G[a+4*c>>2];if(0==e)break;++c;65536<=e?(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023)):d+=String.fromCharCode(e)}return d}
function Ca(a,b,c){void 0===c&&(c=2147483647);if(4>c)return 0;var d=b;c=d+c-4;for(var e=0;e<a.length;++e){var f=a.charCodeAt(e);if(55296<=f&&57343>=f){var k=a.charCodeAt(++e);f=65536+((f&1023)<<10)|k&1023}G[b>>2]=f;b+=4;if(b+4>c)break}G[b>>2]=0;return b-d}function Da(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&++c;b+=4}return b}var Ea,H,D,F,ya,G,I,Fa,Ga,Ha,Ia=[],Ja=[],Ka=[];function La(){var a=h.preRun.shift();Ia.unshift(a)}var J=0,Ma=null,Na=null;
h.preloadedImages={};h.preloadedAudios={};function z(a){if(h.onAbort)h.onAbort(a);B(a);sa=!0;a=new WebAssembly.RuntimeError("abort("+a+"). Build with -s ASSERTIONS=1 for more info.");ba(a);throw a;}function Oa(){return K.startsWith("data:application/octet-stream;base64,")}var K="chess-wasm.wasm";if(!Oa()){var Pa=K;K=h.locateFile?h.locateFile(Pa,y):y+Pa}
function Qa(){var a=K;try{if(a==K&&qa)return new Uint8Array(qa);if(ma)return ma(a);throw"both async and sync fetching of the wasm failed";}catch(b){z(b)}}
function Ra(){if(!qa&&(ea||v)){if("function"===typeof fetch&&!K.startsWith("file://"))return fetch(K,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+K+"'";return a.arrayBuffer()}).catch(function(){return Qa()});if(la)return new Promise(function(a,b){la(K,function(c){a(new Uint8Array(c))},b)})}return Promise.resolve().then(function(){return Qa()})}var Sa,Ta;
function Ua(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(h);else{var c=b.Db;"number"===typeof c?void 0===b.Ca?Ha.get(c)():Ha.get(c)(b.Ca):c(void 0===b.Ca?null:b.Ca)}}}function Va(a){this.U=a-16;this.sb=function(b){G[this.U+8>>2]=b};this.pb=function(b){G[this.U+0>>2]=b};this.qb=function(){G[this.U+4>>2]=0};this.ob=function(){H[this.U+12>>0]=0};this.rb=function(){H[this.U+13>>0]=0};this.gb=function(b,c){this.sb(b);this.pb(c);this.qb();this.ob();this.rb()}}var Wa=0,Xa={};
function Ya(a){for(;a.length;){var b=a.pop();a.pop()(b)}}function Za(a){return this.fromWireType(I[a>>2])}var $a={},L={},ab={};function bb(a){if(void 0===a)return"_unknown";a=a.replace(/[^a-zA-Z0-9_]/g,"$");var b=a.charCodeAt(0);return 48<=b&&57>=b?"_"+a:a}function cb(a,b){a=bb(a);return(new Function("body","return function "+a+'() {\n    "use strict";    return body.apply(this, arguments);\n};\n'))(b)}
function db(a){var b=Error,c=cb(a,function(d){this.name=a;this.message=d;d=Error(d).stack;void 0!==d&&(this.stack=this.toString()+"\n"+d.replace(/^Error(:[^\n]*)?\n/,""))});c.prototype=Object.create(b.prototype);c.prototype.constructor=c;c.prototype.toString=function(){return void 0===this.message?this.name:this.name+": "+this.message};return c}var eb=void 0;function fb(a){throw new eb(a);}
function gb(a,b,c){function d(l){l=c(l);l.length!==a.length&&fb("Mismatched type converter count");for(var r=0;r<a.length;++r)M(a[r],l[r])}a.forEach(function(l){ab[l]=b});var e=Array(b.length),f=[],k=0;b.forEach(function(l,r){L.hasOwnProperty(l)?e[r]=L[l]:(f.push(l),$a.hasOwnProperty(l)||($a[l]=[]),$a[l].push(function(){e[r]=L[l];++k;k===f.length&&d(e)}))});0===f.length&&d(e)}
function hb(a){switch(a){case 1:return 0;case 2:return 1;case 4:return 2;case 8:return 3;default:throw new TypeError("Unknown type size: "+a);}}var ib=void 0;function N(a){for(var b="";D[a];)b+=ib[D[a++]];return b}var jb=void 0;function O(a){throw new jb(a);}
function M(a,b,c){c=c||{};if(!("argPackAdvance"in b))throw new TypeError("registerType registeredInstance requires argPackAdvance");var d=b.name;a||O('type "'+d+'" must have a positive integer typeid pointer');if(L.hasOwnProperty(a)){if(c.fb)return;O("Cannot register type '"+d+"' twice")}L[a]=b;delete ab[a];$a.hasOwnProperty(a)&&(b=$a[a],delete $a[a],b.forEach(function(e){e()}))}function kb(a){O(a.R.Y.W.name+" instance already deleted")}var lb=!1;function mb(){}
function nb(a){--a.count.value;0===a.count.value&&(a.$?a.aa.ia(a.$):a.Y.W.ia(a.U))}function ob(a){if("undefined"===typeof FinalizationGroup)return ob=function(b){return b},a;lb=new FinalizationGroup(function(b){for(var c=b.next();!c.done;c=b.next())c=c.value,c.U?nb(c):console.warn("object already deleted: "+c.U)});ob=function(b){lb.register(b,b.R,b.R);return b};mb=function(b){lb.unregister(b.R)};return ob(a)}var pb=void 0,qb=[];
function rb(){for(;qb.length;){var a=qb.pop();a.R.ma=!1;a["delete"]()}}function P(){}var sb={};function tb(a,b,c){if(void 0===a[b].fa){var d=a[b];a[b]=function(){a[b].fa.hasOwnProperty(arguments.length)||O("Function '"+c+"' called with an invalid number of arguments ("+arguments.length+") - expects one of ("+a[b].fa+")!");return a[b].fa[arguments.length].apply(this,arguments)};a[b].fa=[];a[b].fa[d.ua]=d}}
function ub(a,b){h.hasOwnProperty(a)?(O("Cannot register public name '"+a+"' twice"),tb(h,a,a),h.hasOwnProperty(void 0)&&O("Cannot register multiple overloads of a function with the same number of arguments (undefined)!"),h[a].fa[void 0]=b):h[a]=b}function vb(a,b,c,d,e,f,k,l){this.name=a;this.constructor=b;this.oa=c;this.ia=d;this.ba=e;this.$a=f;this.ta=k;this.Ya=l;this.kb=[]}
function wb(a,b,c){for(;b!==c;)b.ta||O("Expected null or instance of "+c.name+", got an instance of "+b.name),a=b.ta(a),b=b.ba;return a}function xb(a,b){if(null===b)return this.Ea&&O("null is not a valid "+this.name),0;b.R||O('Cannot pass "'+yb(b)+'" as a '+this.name);b.R.U||O("Cannot pass deleted object as a pointer of type "+this.name);return wb(b.R.U,b.R.Y.W,this.W)}
function zb(a,b){if(null===b){this.Ea&&O("null is not a valid "+this.name);if(this.wa){var c=this.Ga();null!==a&&a.push(this.ia,c);return c}return 0}b.R||O('Cannot pass "'+yb(b)+'" as a '+this.name);b.R.U||O("Cannot pass deleted object as a pointer of type "+this.name);!this.va&&b.R.Y.va&&O("Cannot convert argument of type "+(b.R.aa?b.R.aa.name:b.R.Y.name)+" to parameter type "+this.name);c=wb(b.R.U,b.R.Y.W,this.W);if(this.wa)switch(void 0===b.R.$&&O("Passing raw pointer to smart pointer is illegal"),
this.wb){case 0:b.R.aa===this?c=b.R.$:O("Cannot convert argument of type "+(b.R.aa?b.R.aa.name:b.R.Y.name)+" to parameter type "+this.name);break;case 1:c=b.R.$;break;case 2:if(b.R.aa===this)c=b.R.$;else{var d=b.clone();c=this.lb(c,Ab(function(){d["delete"]()}));null!==a&&a.push(this.ia,c)}break;default:O("Unsupporting sharing policy")}return c}
function Bb(a,b){if(null===b)return this.Ea&&O("null is not a valid "+this.name),0;b.R||O('Cannot pass "'+yb(b)+'" as a '+this.name);b.R.U||O("Cannot pass deleted object as a pointer of type "+this.name);b.R.Y.va&&O("Cannot convert argument of type "+b.R.Y.name+" to parameter type "+this.name);return wb(b.R.U,b.R.Y.W,this.W)}function Cb(a,b,c){if(b===c)return a;if(void 0===c.ba)return null;a=Cb(a,b,c.ba);return null===a?null:c.Ya(a)}var Db={};
function Eb(a,b){for(void 0===b&&O("ptr should not be undefined");a.ba;)b=a.ta(b),a=a.ba;return Db[b]}function Fb(a,b){b.Y&&b.U||fb("makeClassHandle requires ptr and ptrType");!!b.aa!==!!b.$&&fb("Both smartPtrType and smartPtr must be specified");b.count={value:1};return ob(Object.create(a,{R:{value:b}}))}
function Q(a,b,c,d){this.name=a;this.W=b;this.Ea=c;this.va=d;this.wa=!1;this.ia=this.lb=this.Ga=this.Ua=this.wb=this.jb=void 0;void 0!==b.ba?this.toWireType=zb:(this.toWireType=d?xb:Bb,this.da=null)}function Gb(a,b){h.hasOwnProperty(a)||fb("Replacing nonexistant public symbol");h[a]=b;h[a].ua=void 0}
function Hb(a,b){var c=[];return function(){c.length=arguments.length;for(var d=0;d<arguments.length;d++)c[d]=arguments[d];a.includes("j")?(d=h["dynCall_"+a],d=c&&c.length?d.apply(null,[b].concat(c)):d.call(null,b)):d=Ha.get(b).apply(null,c);return d}}function R(a,b){a=N(a);var c=a.includes("j")?Hb(a,b):Ha.get(b);"function"!==typeof c&&O("unknown function pointer with signature "+a+": "+b);return c}var Ib=void 0;function Jb(a){a=Kb(a);var b=N(a);S(a);return b}
function Lb(a,b){function c(f){e[f]||L[f]||(ab[f]?ab[f].forEach(c):(d.push(f),e[f]=!0))}var d=[],e={};b.forEach(c);throw new Ib(a+": "+d.map(Jb).join([", "]));}function Mb(a,b){for(var c=[],d=0;d<a;d++)c.push(G[(b>>2)+d]);return c}
function Nb(a){var b=Function;if(!(b instanceof Function))throw new TypeError("new_ called with constructor type "+typeof b+" which is not a function");var c=cb(b.name||"unknownFunctionName",function(){});c.prototype=b.prototype;c=new c;a=b.apply(c,a);return a instanceof Object?a:c}var Ob=[],T=[{},{value:void 0},{value:null},{value:!0},{value:!1}];function Pb(a){4<a&&0===--T[a].Ia&&(T[a]=void 0,Ob.push(a))}
function Ab(a){switch(a){case void 0:return 1;case null:return 2;case !0:return 3;case !1:return 4;default:var b=Ob.length?Ob.pop():T.length;T[b]={Ia:1,value:a};return b}}function yb(a){if(null===a)return"null";var b=typeof a;return"object"===b||"array"===b||"function"===b?a.toString():""+a}function Qb(a,b){switch(b){case 2:return function(c){return this.fromWireType(Fa[c>>2])};case 3:return function(c){return this.fromWireType(Ga[c>>3])};default:throw new TypeError("Unknown float type: "+a);}}
function Rb(a,b,c){switch(b){case 0:return c?function(d){return H[d]}:function(d){return D[d]};case 1:return c?function(d){return F[d>>1]}:function(d){return ya[d>>1]};case 2:return c?function(d){return G[d>>2]}:function(d){return I[d>>2]};default:throw new TypeError("Unknown integer type: "+a);}}var Sb={};
function Tb(){if(!Ub){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"===typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:da||"./this.program"},b;for(b in Sb)a[b]=Sb[b];var c=[];for(b in a)c.push(b+"="+a[b]);Ub=c}return Ub}var Ub;
function Vb(a,b){for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a}function Wb(a){var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=Vb(a.split("/").filter(function(d){return!!d}),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a}
function Xb(a){var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b}function Yb(a){if("/"===a)return"/";a=Wb(a);a=a.replace(/\/$/,"");var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)}
function Zb(){if("object"===typeof crypto&&"function"===typeof crypto.getRandomValues){var a=new Uint8Array(1);return function(){crypto.getRandomValues(a);return a[0]}}if(fa)try{var b=require("crypto");return function(){return b.randomBytes(1)[0]}}catch(c){}return function(){z("randomDevice")}}
function $b(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!==typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=Vb(a.split("/").filter(function(d){return!!d}),!b).join("/");return(b?"/":"")+a||"."}var ac=[];function bc(a,b){ac[a]={input:[],output:[],pa:b};cc(a,dc)}
var dc={open:function(a){var b=ac[a.node.rdev];if(!b)throw new U(43);a.tty=b;a.seekable=!1},close:function(a){a.tty.pa.flush(a.tty)},flush:function(a){a.tty.pa.flush(a.tty)},read:function(a,b,c,d){if(!a.tty||!a.tty.pa.Qa)throw new U(60);for(var e=0,f=0;f<d;f++){try{var k=a.tty.pa.Qa(a.tty)}catch(l){throw new U(29);}if(void 0===k&&0===e)throw new U(6);if(null===k||void 0===k)break;e++;b[c+f]=k}e&&(a.node.timestamp=Date.now());return e},write:function(a,b,c,d){if(!a.tty||!a.tty.pa.Fa)throw new U(60);
try{for(var e=0;e<d;e++)a.tty.pa.Fa(a.tty,b[c+e])}catch(f){throw new U(29);}d&&(a.node.timestamp=Date.now());return e}},fc={Qa:function(a){if(!a.input.length){var b=null;if(fa){var c=Buffer.Va?Buffer.Va(256):new Buffer(256),d=0;try{d=na.readSync(process.stdin.fd,c,0,256,null)}catch(e){if(e.toString().includes("EOF"))d=0;else throw e;}0<d?b=c.slice(0,d).toString("utf-8"):b=null}else"undefined"!=typeof window&&"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==
typeof readline&&(b=readline(),null!==b&&(b+="\n"));if(!b)return null;a.input=ec(b,!0)}return a.input.shift()},Fa:function(a,b){null===b||10===b?(pa(C(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(pa(C(a.output,0)),a.output=[])}},hc={Fa:function(a,b){null===b||10===b?(B(C(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(B(C(a.output,0)),a.output=[])}},V={ea:null,ha:function(){return V.createNode(null,
"/",16895,0)},createNode:function(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new U(63);V.ea||(V.ea={dir:{node:{ja:V.T.ja,ga:V.T.ga,lookup:V.T.lookup,xa:V.T.xa,rename:V.T.rename,unlink:V.T.unlink,rmdir:V.T.rmdir,readdir:V.T.readdir,symlink:V.T.symlink},stream:{la:V.V.la}},file:{node:{ja:V.T.ja,ga:V.T.ga},stream:{la:V.V.la,read:V.V.read,write:V.V.write,Ja:V.V.Ja,Ra:V.V.Ra,Ta:V.V.Ta}},link:{node:{ja:V.T.ja,ga:V.T.ga,readlink:V.T.readlink},stream:{}},Ka:{node:{ja:V.T.ja,ga:V.T.ga},stream:ic}});
c=jc(a,b,c,d);16384===(c.mode&61440)?(c.T=V.ea.dir.node,c.V=V.ea.dir.stream,c.S={}):32768===(c.mode&61440)?(c.T=V.ea.file.node,c.V=V.ea.file.stream,c.X=0,c.S=null):40960===(c.mode&61440)?(c.T=V.ea.link.node,c.V=V.ea.link.stream):8192===(c.mode&61440)&&(c.T=V.ea.Ka.node,c.V=V.ea.Ka.stream);c.timestamp=Date.now();a&&(a.S[b]=c,a.timestamp=c.timestamp);return c},Eb:function(a){return a.S?a.S.subarray?a.S.subarray(0,a.X):new Uint8Array(a.S):new Uint8Array(0)},Ma:function(a,b){var c=a.S?a.S.length:0;c>=
b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),c=a.S,a.S=new Uint8Array(b),0<a.X&&a.S.set(c.subarray(0,a.X),0))},mb:function(a,b){if(a.X!=b)if(0==b)a.S=null,a.X=0;else{var c=a.S;a.S=new Uint8Array(b);c&&a.S.set(c.subarray(0,Math.min(b,a.X)));a.X=b}},T:{ja:function(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;16384===(a.mode&61440)?b.size=4096:32768===(a.mode&61440)?b.size=a.X:40960===(a.mode&61440)?b.size=a.link.length:
b.size=0;b.atime=new Date(a.timestamp);b.mtime=new Date(a.timestamp);b.ctime=new Date(a.timestamp);b.Wa=4096;b.blocks=Math.ceil(b.size/b.Wa);return b},ga:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==b.size&&V.mb(a,b.size)},lookup:function(){throw kc[44];},xa:function(a,b,c,d){return V.createNode(a,b,c,d)},rename:function(a,b,c){if(16384===(a.mode&61440)){try{var d=lc(b,c)}catch(f){}if(d)for(var e in d.S)throw new U(55);}delete a.parent.S[a.name];
a.parent.timestamp=Date.now();a.name=c;b.S[c]=a;b.timestamp=a.parent.timestamp;a.parent=b},unlink:function(a,b){delete a.S[b];a.timestamp=Date.now()},rmdir:function(a,b){var c=lc(a,b),d;for(d in c.S)throw new U(55);delete a.S[b];a.timestamp=Date.now()},readdir:function(a){var b=[".",".."],c;for(c in a.S)a.S.hasOwnProperty(c)&&b.push(c);return b},symlink:function(a,b,c){a=V.createNode(a,b,41471,0);a.link=c;return a},readlink:function(a){if(40960!==(a.mode&61440))throw new U(28);return a.link}},V:{read:function(a,
b,c,d,e){var f=a.node.S;if(e>=a.node.X)return 0;a=Math.min(a.node.X-e,d);if(8<a&&f.subarray)b.set(f.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=f[e+d];return a},write:function(a,b,c,d,e,f){if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.S||a.S.subarray)){if(f)return a.S=b.subarray(c,c+d),a.X=d;if(0===a.X&&0===e)return a.S=b.slice(c,c+d),a.X=d;if(e+d<=a.X)return a.S.set(b.subarray(c,c+d),e),d}V.Ma(a,e+d);if(a.S.subarray&&b.subarray)a.S.set(b.subarray(c,c+d),e);else for(f=0;f<d;f++)a.S[e+
f]=b[c+f];a.X=Math.max(a.X,e+d);return d},la:function(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.X);if(0>b)throw new U(28);return b},Ja:function(a,b,c){V.Ma(a.node,b+c);a.node.X=Math.max(a.node.X,b+c)},Ra:function(a,b,c,d,e,f){if(0!==b)throw new U(28);if(32768!==(a.node.mode&61440))throw new U(43);a=a.node.S;if(f&2||a.buffer!==Ea){if(0<d||d+c<a.length)a.subarray?a=a.subarray(d,d+c):a=Array.prototype.slice.call(a,d,d+c);d=!0;f=16384*Math.ceil(c/16384);for(b=mc(f);c<f;)H[b+
c++]=0;c=b;if(!c)throw new U(48);H.set(a,c)}else d=!1,c=a.byteOffset;return{U:c,Cb:d}},Ta:function(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new U(43);if(e&2)return 0;V.V.write(a,b,0,d,c,!1);return 0}}},nc=null,oc={},pc=[],qc=1,rc=null,uc={},U=null,kc={};
function W(a,b){a=$b("/",a);b=b||{};if(!a)return{path:"",node:null};var c={Pa:!0,Ha:0},d;for(d in c)void 0===b[d]&&(b[d]=c[d]);if(8<b.Ha)throw new U(32);a=Vb(a.split("/").filter(function(k){return!!k}),!1);var e=nc;c="/";for(d=0;d<a.length;d++){var f=d===a.length-1;if(f&&b.parent)break;e=lc(e,a[d]);c=Wb(c+"/"+a[d]);e.ya&&(!f||f&&b.Pa)&&(e=e.ya.root);if(!f||b.Oa)for(f=0;40960===(e.mode&61440);)if(e=vc(c),c=$b(Xb(c),e),e=W(c,{Ha:b.Ha}).node,40<f++)throw new U(32);}return{path:c,node:e}}
function wc(a){for(var b;;){if(a===a.parent)return a=a.ha.Sa,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}}function xc(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%rc.length}function lc(a,b){var c;if(c=a.T.lookup?0:2)throw new U(c,a);for(c=rc[xc(a.id,b)];c;c=c.ib){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.T.lookup(a,b)}function jc(a,b,c,d){a=new yc(a,b,c,d);b=xc(a.parent.id,a.name);a.ib=rc[b];return rc[b]=a}
var zc={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090};function Ac(a,b){try{return lc(a,b),20}catch(c){}return 0}function Bc(){var a=4096;for(var b=0;b<=a;b++)if(!pc[b])return b;throw new U(33);}function Cc(a){Dc||(Dc=function(){},Dc.prototype={});var b=new Dc,c;for(c in a)b[c]=a[c];a=b;b=Bc();a.fd=b;return pc[b]=a}var ic={open:function(a){a.V=oc[a.node.rdev].V;a.V.open&&a.V.open(a)},la:function(){throw new U(70);}};function cc(a,b){oc[a]={V:b}}
function Ec(a,b){var c="/"===b,d=!b;if(c&&nc)throw new U(10);if(!c&&!d){var e=W(b,{Pa:!1});b=e.path;e=e.node;if(e.ya)throw new U(10);if(16384!==(e.mode&61440))throw new U(54);}b={type:a,Gb:{},Sa:b,hb:[]};a=a.ha(b);a.ha=b;b.root=a;c?nc=a:e&&(e.ya=b,e.ha&&e.ha.hb.push(b))}function Fc(a,b,c){var d=W(a,{parent:!0}).node;a=Yb(a);if(!a||"."===a||".."===a)throw new U(28);var e=Ac(d,a);if(e)throw new U(e);if(!d.T.xa)throw new U(63);return d.T.xa(d,a,b,c)}function Z(a){return Fc(a,16895,0)}
function Gc(a,b,c){"undefined"===typeof c&&(c=b,b=438);Fc(a,b|8192,c)}function Hc(a,b){if(!$b(a))throw new U(44);var c=W(b,{parent:!0}).node;if(!c)throw new U(44);b=Yb(b);var d=Ac(c,b);if(d)throw new U(d);if(!c.T.symlink)throw new U(63);c.T.symlink(c,b,a)}function vc(a){a=W(a).node;if(!a)throw new U(44);if(!a.T.readlink)throw new U(28);return $b(wc(a.parent),a.T.readlink(a))}
function Ic(a,b){if(""===a)throw new U(44);if("string"===typeof b){var c=zc[b];if("undefined"===typeof c)throw Error("Unknown file open mode: "+b);b=c}var d=b&64?("undefined"===typeof d?438:d)&4095|32768:0;if("object"===typeof a)var e=a;else{a=Wb(a);try{e=W(a,{Oa:!(b&131072)}).node}catch(f){}}c=!1;if(b&64)if(e){if(b&128)throw new U(20);}else e=Fc(a,d,0),c=!0;if(!e)throw new U(44);8192===(e.mode&61440)&&(b&=-513);if(b&65536&&16384!==(e.mode&61440))throw new U(54);if(!c){if(e)if(40960===(e.mode&61440))d=
32;else{if(d=16384===(e.mode&61440))d=["r","w","rw"][b&3],b&512&&(d+="w"),d="r"!==d||b&512;d=d?31:0}else d=44;if(d)throw new U(d);}if(b&512){d=e;d="string"===typeof d?W(d,{Oa:!0}).node:d;if(!d.T.ga)throw new U(63);if(16384===(d.mode&61440))throw new U(31);if(32768!==(d.mode&61440))throw new U(28);d.T.ga(d,{size:0,timestamp:Date.now()})}b&=-131713;e=Cc({node:e,path:wc(e),flags:b,seekable:!0,position:0,V:e.V,Bb:[],error:!1});e.V.open&&e.V.open(e);!h.logReadFiles||b&1||(Jc||(Jc={}),a in Jc||(Jc[a]=1,
B("FS.trackingDelegate error on read file: "+a)));try{uc.onOpenFile&&(e=0,1!==(b&2097155)&&(e|=1),0!==(b&2097155)&&(e|=2),uc.onOpenFile(a,e))}catch(f){B("FS.trackingDelegate['onOpenFile']('"+a+"', flags) threw an exception: "+f.message)}}function Kc(a,b,c){if(null===a.fd)throw new U(8);if(!a.seekable||!a.V.la)throw new U(70);if(0!=c&&1!=c&&2!=c)throw new U(28);a.position=a.V.la(a,b,c);a.Bb=[]}
function Lc(){U||(U=function(a,b){this.node=b;this.nb=function(c){this.na=c};this.nb(a);this.message="FS error"},U.prototype=Error(),U.prototype.constructor=U,[44].forEach(function(a){kc[a]=new U(a);kc[a].stack="<generic error, no stack>"}))}var Mc;function Nc(a,b){var c=0;a&&(c|=365);b&&(c|=146);return c}
function Oc(a,b,c){a=Wb("/dev/"+a);var d=Nc(!!b,!!c);Pc||(Pc=64);var e=Pc++<<8|0;cc(e,{open:function(f){f.seekable=!1},close:function(){c&&c.buffer&&c.buffer.length&&c(10)},read:function(f,k,l,r){for(var m=0,q=0;q<r;q++){try{var w=b()}catch(x){throw new U(29);}if(void 0===w&&0===m)throw new U(6);if(null===w||void 0===w)break;m++;k[l+q]=w}m&&(f.node.timestamp=Date.now());return m},write:function(f,k,l,r){for(var m=0;m<r;m++)try{c(k[l+m])}catch(q){throw new U(29);}r&&(f.node.timestamp=Date.now());return m}});
Gc(a,d,e)}var Pc,Qc={},Dc,Jc;function Rc(a){a=pc[a];if(!a)throw new U(8);return a}function Sc(a){return 0===a%4&&(0!==a%100||0===a%400)}function Tc(a,b){for(var c=0,d=0;d<=b;c+=a[d++]);return c}var Uc=[31,29,31,30,31,30,31,31,30,31,30,31],Vc=[31,28,31,30,31,30,31,31,30,31,30,31];
function Wc(a,b){for(a=new Date(a.getTime());0<b;){var c=a.getMonth(),d=(Sc(a.getFullYear())?Uc:Vc)[c];if(b>d-a.getDate())b-=d-a.getDate()+1,a.setDate(1),11>c?a.setMonth(c+1):(a.setMonth(0),a.setFullYear(a.getFullYear()+1));else{a.setDate(a.getDate()+b);break}}return a}
function Xc(a,b,c,d){function e(g,p,u){for(g="number"===typeof g?g.toString():g||"";g.length<p;)g=u[0]+g;return g}function f(g,p){return e(g,p,"0")}function k(g,p){function u(E){return 0>E?-1:0<E?1:0}var t;0===(t=u(g.getFullYear()-p.getFullYear()))&&0===(t=u(g.getMonth()-p.getMonth()))&&(t=u(g.getDate()-p.getDate()));return t}function l(g){switch(g.getDay()){case 0:return new Date(g.getFullYear()-1,11,29);case 1:return g;case 2:return new Date(g.getFullYear(),0,3);case 3:return new Date(g.getFullYear(),
0,2);case 4:return new Date(g.getFullYear(),0,1);case 5:return new Date(g.getFullYear()-1,11,31);case 6:return new Date(g.getFullYear()-1,11,30)}}function r(g){g=Wc(new Date(g.Z+1900,0,1),g.Ba);var p=new Date(g.getFullYear()+1,0,4),u=l(new Date(g.getFullYear(),0,4));p=l(p);return 0>=k(u,g)?0>=k(p,g)?g.getFullYear()+1:g.getFullYear():g.getFullYear()-1}var m=G[d+40>>2];d={zb:G[d>>2],yb:G[d+4>>2],za:G[d+8>>2],sa:G[d+12>>2],qa:G[d+16>>2],Z:G[d+20>>2],Aa:G[d+24>>2],Ba:G[d+28>>2],Hb:G[d+32>>2],xb:G[d+36>>
2],Ab:m?m?C(D,m,void 0):"":""};c=c?C(D,c,void 0):"";m={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S","%Ec":"%c","%EC":"%C","%Ex":"%m/%d/%y","%EX":"%H:%M:%S","%Ey":"%y","%EY":"%Y","%Od":"%d","%Oe":"%e","%OH":"%H","%OI":"%I","%Om":"%m","%OM":"%M","%OS":"%S","%Ou":"%u","%OU":"%U","%OV":"%V","%Ow":"%w","%OW":"%W","%Oy":"%y"};for(var q in m)c=c.replace(new RegExp(q,"g"),m[q]);var w="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),
x="January February March April May June July August September October November December".split(" ");m={"%a":function(g){return w[g.Aa].substring(0,3)},"%A":function(g){return w[g.Aa]},"%b":function(g){return x[g.qa].substring(0,3)},"%B":function(g){return x[g.qa]},"%C":function(g){return f((g.Z+1900)/100|0,2)},"%d":function(g){return f(g.sa,2)},"%e":function(g){return e(g.sa,2," ")},"%g":function(g){return r(g).toString().substring(2)},"%G":function(g){return r(g)},"%H":function(g){return f(g.za,
2)},"%I":function(g){g=g.za;0==g?g=12:12<g&&(g-=12);return f(g,2)},"%j":function(g){return f(g.sa+Tc(Sc(g.Z+1900)?Uc:Vc,g.qa-1),3)},"%m":function(g){return f(g.qa+1,2)},"%M":function(g){return f(g.yb,2)},"%n":function(){return"\n"},"%p":function(g){return 0<=g.za&&12>g.za?"AM":"PM"},"%S":function(g){return f(g.zb,2)},"%t":function(){return"\t"},"%u":function(g){return g.Aa||7},"%U":function(g){var p=new Date(g.Z+1900,0,1),u=0===p.getDay()?p:Wc(p,7-p.getDay());g=new Date(g.Z+1900,g.qa,g.sa);return 0>
k(u,g)?f(Math.ceil((31-u.getDate()+(Tc(Sc(g.getFullYear())?Uc:Vc,g.getMonth()-1)-31)+g.getDate())/7),2):0===k(u,p)?"01":"00"},"%V":function(g){var p=new Date(g.Z+1901,0,4),u=l(new Date(g.Z+1900,0,4));p=l(p);var t=Wc(new Date(g.Z+1900,0,1),g.Ba);return 0>k(t,u)?"53":0>=k(p,t)?"01":f(Math.ceil((u.getFullYear()<g.Z+1900?g.Ba+32-u.getDate():g.Ba+1-u.getDate())/7),2)},"%w":function(g){return g.Aa},"%W":function(g){var p=new Date(g.Z,0,1),u=1===p.getDay()?p:Wc(p,0===p.getDay()?1:7-p.getDay()+1);g=new Date(g.Z+
1900,g.qa,g.sa);return 0>k(u,g)?f(Math.ceil((31-u.getDate()+(Tc(Sc(g.getFullYear())?Uc:Vc,g.getMonth()-1)-31)+g.getDate())/7),2):0===k(u,p)?"01":"00"},"%y":function(g){return(g.Z+1900).toString().substring(2)},"%Y":function(g){return g.Z+1900},"%z":function(g){g=g.xb;var p=0<=g;g=Math.abs(g)/60;return(p?"+":"-")+String("0000"+(g/60*100+g%60)).slice(-4)},"%Z":function(g){return g.Ab},"%%":function(){return"%"}};for(q in m)c.includes(q)&&(c=c.replace(new RegExp(q,"g"),m[q](d)));q=ec(c,!1);if(q.length>
b)return 0;H.set(q,a);return q.length-1}eb=h.InternalError=db("InternalError");for(var Yc=Array(256),Zc=0;256>Zc;++Zc)Yc[Zc]=String.fromCharCode(Zc);ib=Yc;jb=h.BindingError=db("BindingError");P.prototype.isAliasOf=function(a){if(!(this instanceof P&&a instanceof P))return!1;var b=this.R.Y.W,c=this.R.U,d=a.R.Y.W;for(a=a.R.U;b.ba;)c=b.ta(c),b=b.ba;for(;d.ba;)a=d.ta(a),d=d.ba;return b===d&&c===a};
P.prototype.clone=function(){this.R.U||kb(this);if(this.R.ra)return this.R.count.value+=1,this;var a=ob,b=Object,c=b.create,d=Object.getPrototypeOf(this),e=this.R;a=a(c.call(b,d,{R:{value:{count:e.count,ma:e.ma,ra:e.ra,U:e.U,Y:e.Y,$:e.$,aa:e.aa}}}));a.R.count.value+=1;a.R.ma=!1;return a};P.prototype["delete"]=function(){this.R.U||kb(this);this.R.ma&&!this.R.ra&&O("Object already scheduled for deletion");mb(this);nb(this.R);this.R.ra||(this.R.$=void 0,this.R.U=void 0)};P.prototype.isDeleted=function(){return!this.R.U};
P.prototype.deleteLater=function(){this.R.U||kb(this);this.R.ma&&!this.R.ra&&O("Object already scheduled for deletion");qb.push(this);1===qb.length&&pb&&pb(rb);this.R.ma=!0;return this};Q.prototype.ab=function(a){this.Ua&&(a=this.Ua(a));return a};Q.prototype.La=function(a){this.ia&&this.ia(a)};Q.prototype.argPackAdvance=8;Q.prototype.readValueFromPointer=Za;Q.prototype.deleteObject=function(a){if(null!==a)a["delete"]()};
Q.prototype.fromWireType=function(a){function b(){return this.wa?Fb(this.W.oa,{Y:this.jb,U:c,aa:this,$:a}):Fb(this.W.oa,{Y:this,U:a})}var c=this.ab(a);if(!c)return this.La(a),null;var d=Eb(this.W,c);if(void 0!==d){if(0===d.R.count.value)return d.R.U=c,d.R.$=a,d.clone();d=d.clone();this.La(a);return d}d=this.W.$a(c);d=sb[d];if(!d)return b.call(this);d=this.va?d.Xa:d.pointerType;var e=Cb(c,this.W,d.W);return null===e?b.call(this):this.wa?Fb(d.W.oa,{Y:d,U:e,aa:this,$:a}):Fb(d.W.oa,{Y:d,U:e})};
h.getInheritedInstanceCount=function(){return Object.keys(Db).length};h.getLiveInheritedInstances=function(){var a=[],b;for(b in Db)Db.hasOwnProperty(b)&&a.push(Db[b]);return a};h.flushPendingDeletes=rb;h.setDelayFunction=function(a){pb=a;qb.length&&pb&&pb(rb)};Ib=h.UnboundTypeError=db("UnboundTypeError");h.count_emval_handles=function(){for(var a=0,b=5;b<T.length;++b)void 0!==T[b]&&++a;return a};h.get_first_emval=function(){for(var a=5;a<T.length;++a)if(void 0!==T[a])return T[a];return null};
function yc(a,b,c,d){a||(a=this);this.parent=a;this.ha=a.ha;this.ya=null;this.id=qc++;this.name=b;this.mode=c;this.T={};this.V={};this.rdev=d}Object.defineProperties(yc.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}}});Lc();rc=Array(4096);Ec(V,"/");Z("/tmp");Z("/home");Z("/home/web_user");
(function(){Z("/dev");cc(259,{read:function(){return 0},write:function(b,c,d,e){return e}});Gc("/dev/null",259);bc(1280,fc);bc(1536,hc);Gc("/dev/tty",1280);Gc("/dev/tty1",1536);var a=Zb();Oc("random",a);Oc("urandom",a);Z("/dev/shm");Z("/dev/shm/tmp")})();
(function(){Z("/proc");var a=Z("/proc/self");Z("/proc/self/fd");Ec({ha:function(){var b=jc(a,"fd",16895,73);b.T={lookup:function(c,d){var e=pc[+d];if(!e)throw new U(8);c={parent:null,ha:{Sa:"fake"},T:{readlink:function(){return e.path}}};return c.parent=c}};return b}},"/proc/self/fd")})();function ec(a,b){var c=Array(va(a)+1);a=ua(a,c,0,c.length);b&&(c.length=a);return c}
var $c={c:function(a){return mc(a+16)+16},b:function(a,b,c){(new Va(a)).gb(b,c);Wa++;throw a;},z:function(a){var b=Xa[a];delete Xa[a];var c=b.Ga,d=b.ia,e=b.Na,f=e.map(function(k){return k.eb}).concat(e.map(function(k){return k.ub}));gb([a],f,function(k){var l={};e.forEach(function(r,m){var q=k[m],w=r.bb,x=r.cb,g=k[m+e.length],p=r.tb,u=r.vb;l[r.Za]={read:function(t){return q.fromWireType(w(x,t))},write:function(t,E){var A=[];p(u,t,g.toWireType(A,E));Ya(A)}}});return[{name:b.name,fromWireType:function(r){var m=
{},q;for(q in l)m[q]=l[q].read(r);d(r);return m},toWireType:function(r,m){for(var q in l)if(!(q in m))throw new TypeError('Missing field:  "'+q+'"');var w=c();for(q in l)l[q].write(w,m[q]);null!==r&&r.push(d,w);return w},argPackAdvance:8,readValueFromPointer:Za,da:d}]})},B:function(a,b,c,d,e){var f=hb(c);b=N(b);M(a,{name:b,fromWireType:function(k){return!!k},toWireType:function(k,l){return l?d:e},argPackAdvance:8,readValueFromPointer:function(k){if(1===c)var l=H;else if(2===c)l=F;else if(4===c)l=
G;else throw new TypeError("Unknown boolean type size: "+b);return this.fromWireType(l[k>>f])},da:null})},i:function(a,b,c,d,e,f,k,l,r,m,q,w,x){q=N(q);f=R(e,f);l&&(l=R(k,l));m&&(m=R(r,m));x=R(w,x);var g=bb(q);ub(g,function(){Lb("Cannot construct "+q+" due to unbound types",[d])});gb([a,b,c],d?[d]:[],function(p){p=p[0];if(d){var u=p.W;var t=u.oa}else t=P.prototype;p=cb(g,function(){if(Object.getPrototypeOf(this)!==E)throw new jb("Use 'new' to construct "+q);if(void 0===A.ka)throw new jb(q+" has no accessible constructor");
var X=A.ka[arguments.length];if(void 0===X)throw new jb("Tried to invoke ctor of "+q+" with invalid number of parameters ("+arguments.length+") - expected ("+Object.keys(A.ka).toString()+") parameters instead!");return X.apply(this,arguments)});var E=Object.create(t,{constructor:{value:p}});p.prototype=E;var A=new vb(q,p,E,x,u,f,l,m);u=new Q(q,A,!0,!1);t=new Q(q+"*",A,!1,!1);var ha=new Q(q+" const*",A,!1,!0);sb[a]={pointerType:t,Xa:ha};Gb(g,p);return[u,t,ha]})},h:function(a,b,c,d,e,f){assert(0<b);
var k=Mb(b,c);e=R(d,e);var l=[f],r=[];gb([],[a],function(m){m=m[0];var q="constructor "+m.name;void 0===m.W.ka&&(m.W.ka=[]);if(void 0!==m.W.ka[b-1])throw new jb("Cannot register multiple constructors with identical number of parameters ("+(b-1)+") for class '"+m.name+"'! Overload resolution is currently only performed using the parameter count, not actual type info!");m.W.ka[b-1]=function(){Lb("Cannot construct "+m.name+" due to unbound types",k)};gb([],k,function(w){m.W.ka[b-1]=function(){arguments.length!==
b-1&&O(q+" called with "+arguments.length+" arguments, expected "+(b-1));r.length=0;l.length=b;for(var x=1;x<b;++x)l[x]=w[x].toWireType(r,arguments[x-1]);x=e.apply(null,l);Ya(r);return w[0].fromWireType(x)};return[]});return[]})},a:function(a,b,c,d,e,f,k,l){var r=Mb(c,d);b=N(b);f=R(e,f);gb([],[a],function(m){function q(){Lb("Cannot call "+w+" due to unbound types",r)}m=m[0];var w=m.name+"."+b;l&&m.W.kb.push(b);var x=m.W.oa,g=x[b];void 0===g||void 0===g.fa&&g.className!==m.name&&g.ua===c-2?(q.ua=c-
2,q.className=m.name,x[b]=q):(tb(x,b,w),x[b].fa[c-2]=q);gb([],r,function(p){var u=w,t=m,E=f,A=p.length;2>A&&O("argTypes array size mismatch! Must at least get return value and 'this' types!");var ha=null!==p[1]&&null!==t,X=!1;for(t=1;t<p.length;++t)if(null!==p[t]&&void 0===p[t].da){X=!0;break}var sc="void"!==p[0].name,Y="",ia="";for(t=0;t<A-2;++t)Y+=(0!==t?", ":"")+"arg"+t,ia+=(0!==t?", ":"")+"arg"+t+"Wired";u="return function "+bb(u)+"("+Y+") {\nif (arguments.length !== "+(A-2)+") {\nthrowBindingError('function "+
u+" called with ' + arguments.length + ' arguments, expected "+(A-2)+" args!');\n}\n";X&&(u+="var destructors = [];\n");var tc=X?"destructors":"null";Y="throwBindingError invoker fn runDestructors retType classParam".split(" ");E=[O,E,k,Ya,p[0],p[1]];ha&&(u+="var thisWired = classParam.toWireType("+tc+", this);\n");for(t=0;t<A-2;++t)u+="var arg"+t+"Wired = argType"+t+".toWireType("+tc+", arg"+t+"); // "+p[t+2].name+"\n",Y.push("argType"+t),E.push(p[t+2]);ha&&(ia="thisWired"+(0<ia.length?", ":"")+
ia);u+=(sc?"var rv = ":"")+"invoker(fn"+(0<ia.length?", ":"")+ia+");\n";if(X)u+="runDestructors(destructors);\n";else for(t=ha?1:2;t<p.length;++t)A=1===t?"thisWired":"arg"+(t-2)+"Wired",null!==p[t].da&&(u+=A+"_dtor("+A+"); // "+p[t].name+"\n",Y.push(A+"_dtor"),E.push(p[t].da));sc&&(u+="var ret = retType.fromWireType(rv);\nreturn ret;\n");Y.push(u+"}\n");p=Nb(Y).apply(null,E);void 0===x[b].fa?(p.ua=c-2,x[b]=p):x[b].fa[c-2]=p;return[]});return[]})},A:function(a,b){b=N(b);M(a,{name:b,fromWireType:function(c){var d=
T[c].value;Pb(c);return d},toWireType:function(c,d){return Ab(d)},argPackAdvance:8,readValueFromPointer:Za,da:null})},n:function(a,b,c){c=hb(c);b=N(b);M(a,{name:b,fromWireType:function(d){return d},toWireType:function(d,e){if("number"!==typeof e&&"boolean"!==typeof e)throw new TypeError('Cannot convert "'+yb(e)+'" to '+this.name);return e},argPackAdvance:8,readValueFromPointer:Qb(b,c),da:null})},f:function(a,b,c,d,e){function f(m){return m}b=N(b);-1===e&&(e=4294967295);var k=hb(c);if(0===d){var l=
32-8*c;f=function(m){return m<<l>>>l}}var r=b.includes("unsigned");M(a,{name:b,fromWireType:f,toWireType:function(m,q){if("number"!==typeof q&&"boolean"!==typeof q)throw new TypeError('Cannot convert "'+yb(q)+'" to '+this.name);if(q<d||q>e)throw new TypeError('Passing a number "'+yb(q)+'" from JS side to C/C++ side to an argument of type "'+b+'", which is outside the valid range ['+d+", "+e+"]!");return r?q>>>0:q|0},argPackAdvance:8,readValueFromPointer:Rb(b,k,0!==d),da:null})},d:function(a,b,c){function d(f){f>>=
2;var k=I;return new e(Ea,k[f+1],k[f])}var e=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array][b];c=N(c);M(a,{name:c,fromWireType:d,argPackAdvance:8,readValueFromPointer:d},{fb:!0})},o:function(a,b){b=N(b);var c="std::string"===b;M(a,{name:b,fromWireType:function(d){var e=I[d>>2];if(c)for(var f=d+4,k=0;k<=e;++k){var l=d+4+k;if(k==e||0==D[l]){f=f?C(D,f,l-f):"";if(void 0===r)var r=f;else r+=String.fromCharCode(0),r+=f;f=l+1}}else{r=Array(e);for(k=0;k<e;++k)r[k]=
String.fromCharCode(D[d+4+k]);r=r.join("")}S(d);return r},toWireType:function(d,e){e instanceof ArrayBuffer&&(e=new Uint8Array(e));var f="string"===typeof e;f||e instanceof Uint8Array||e instanceof Uint8ClampedArray||e instanceof Int8Array||O("Cannot pass non-string to std::string");var k=(c&&f?function(){return va(e)}:function(){return e.length})(),l=mc(4+k+1);I[l>>2]=k;if(c&&f)ua(e,D,l+4,k+1);else if(f)for(f=0;f<k;++f){var r=e.charCodeAt(f);255<r&&(S(l),O("String has UTF-16 code units that do not fit in 8 bits"));
D[l+4+f]=r}else for(f=0;f<k;++f)D[l+4+f]=e[f];null!==d&&d.push(S,l);return l},argPackAdvance:8,readValueFromPointer:Za,da:function(d){S(d)}})},k:function(a,b,c){c=N(c);if(2===b){var d=xa;var e=za;var f=Aa;var k=function(){return ya};var l=1}else 4===b&&(d=Ba,e=Ca,f=Da,k=function(){return I},l=2);M(a,{name:c,fromWireType:function(r){for(var m=I[r>>2],q=k(),w,x=r+4,g=0;g<=m;++g){var p=r+4+g*b;if(g==m||0==q[p>>l])x=d(x,p-x),void 0===w?w=x:(w+=String.fromCharCode(0),w+=x),x=p+b}S(r);return w},toWireType:function(r,
m){"string"!==typeof m&&O("Cannot pass non-string to C++ string type "+c);var q=f(m),w=mc(4+q+b);I[w>>2]=q>>l;e(m,w+4,q+b);null!==r&&r.push(S,w);return w},argPackAdvance:8,readValueFromPointer:Za,da:function(r){S(r)}})},D:function(a,b,c,d,e,f){Xa[a]={name:N(b),Ga:R(c,d),ia:R(e,f),Na:[]}},e:function(a,b,c,d,e,f,k,l,r,m){Xa[a].Na.push({Za:N(b),eb:c,bb:R(d,e),cb:f,ub:k,tb:R(l,r),vb:m})},C:function(a,b){b=N(b);M(a,{Fb:!0,name:b,argPackAdvance:0,fromWireType:function(){},toWireType:function(){}})},p:Pb,
l:function(a){4<a&&(T[a].Ia+=1)},g:function(a,b){var c=L[a];void 0===c&&O("_emval_take_value has unknown type "+Jb(a));a=c.readValueFromPointer(b);return Ab(a)},j:function(){z()},s:function(a,b,c){D.copyWithin(a,b,b+c)},t:function(){z("OOM")},v:function(a,b){try{var c=0;Tb().forEach(function(d,e){var f=b+c;e=G[a+4*e>>2]=f;for(f=0;f<d.length;++f)H[e++>>0]=d.charCodeAt(f);H[e>>0]=0;c+=d.length+1});return 0}catch(d){return"undefined"!==typeof Qc&&d instanceof U||z(d),d.na}},w:function(a,b){try{var c=
Tb();G[a>>2]=c.length;var d=0;c.forEach(function(e){d+=e.length+1});G[b>>2]=d;return 0}catch(e){return"undefined"!==typeof Qc&&e instanceof U||z(e),e.na}},y:function(a){try{var b=Rc(a);if(null===b.fd)throw new U(8);b.Da&&(b.Da=null);try{b.V.close&&b.V.close(b)}catch(c){throw c;}finally{pc[b.fd]=null}b.fd=null;return 0}catch(c){return"undefined"!==typeof Qc&&c instanceof U||z(c),c.na}},x:function(a,b,c,d){try{a:{for(var e=Rc(a),f=a=0;f<c;f++){var k=G[b+(8*f+4)>>2],l=e,r=G[b+8*f>>2],m=k,q=void 0,w=
H;if(0>m||0>q)throw new U(28);if(null===l.fd)throw new U(8);if(1===(l.flags&2097155))throw new U(8);if(16384===(l.node.mode&61440))throw new U(31);if(!l.V.read)throw new U(28);var x="undefined"!==typeof q;if(!x)q=l.position;else if(!l.seekable)throw new U(70);var g=l.V.read(l,w,r,m,q);x||(l.position+=g);var p=g;if(0>p){var u=-1;break a}a+=p;if(p<k)break}u=a}G[d>>2]=u;return 0}catch(t){return"undefined"!==typeof Qc&&t instanceof U||z(t),t.na}},q:function(a,b,c,d,e){try{var f=Rc(a);a=4294967296*c+(b>>>
0);if(-9007199254740992>=a||9007199254740992<=a)return-61;Kc(f,a,d);Ta=[f.position>>>0,(Sa=f.position,1<=+Math.abs(Sa)?0<Sa?(Math.min(+Math.floor(Sa/4294967296),4294967295)|0)>>>0:~~+Math.ceil((Sa-+(~~Sa>>>0))/4294967296)>>>0:0)];G[e>>2]=Ta[0];G[e+4>>2]=Ta[1];f.Da&&0===a&&0===d&&(f.Da=null);return 0}catch(k){return"undefined"!==typeof Qc&&k instanceof U||z(k),k.na}},m:function(a,b,c,d){try{a:{for(var e=Rc(a),f=a=0;f<c;f++){var k=e,l=G[b+8*f>>2],r=G[b+(8*f+4)>>2],m=void 0,q=H;if(0>r||0>m)throw new U(28);
if(null===k.fd)throw new U(8);if(0===(k.flags&2097155))throw new U(8);if(16384===(k.node.mode&61440))throw new U(31);if(!k.V.write)throw new U(28);k.seekable&&k.flags&1024&&Kc(k,0,2);var w="undefined"!==typeof m;if(!w)m=k.position;else if(!k.seekable)throw new U(70);var x=k.V.write(k,q,l,r,m,void 0);w||(k.position+=x);try{if(k.path&&uc.onWriteToFile)uc.onWriteToFile(k.path)}catch(u){B("FS.trackingDelegate['onWriteToFile']('"+k.path+"') threw an exception: "+u.message)}var g=x;if(0>g){var p=-1;break a}a+=
g}p=a}G[d>>2]=p;return 0}catch(u){return"undefined"!==typeof Qc&&u instanceof U||z(u),u.na}},r:function(){},u:function(a,b,c,d){return Xc(a,b,c,d)}};
(function(){function a(e){h.asm=e.exports;ra=h.asm.E;Ea=e=ra.buffer;h.HEAP8=H=new Int8Array(e);h.HEAP16=F=new Int16Array(e);h.HEAP32=G=new Int32Array(e);h.HEAPU8=D=new Uint8Array(e);h.HEAPU16=ya=new Uint16Array(e);h.HEAPU32=I=new Uint32Array(e);h.HEAPF32=Fa=new Float32Array(e);h.HEAPF64=Ga=new Float64Array(e);Ha=h.asm.H;Ja.unshift(h.asm.F);J--;h.monitorRunDependencies&&h.monitorRunDependencies(J);0==J&&(null!==Ma&&(clearInterval(Ma),Ma=null),Na&&(e=Na,Na=null,e()))}function b(e){a(e.instance)}function c(e){return Ra().then(function(f){return WebAssembly.instantiate(f,
d)}).then(e,function(f){B("failed to asynchronously prepare wasm: "+f);z(f)})}var d={a:$c};J++;h.monitorRunDependencies&&h.monitorRunDependencies(J);if(h.instantiateWasm)try{return h.instantiateWasm(d,a)}catch(e){return B("Module.instantiateWasm callback failed with error: "+e),!1}(function(){return qa||"function"!==typeof WebAssembly.instantiateStreaming||Oa()||K.startsWith("file://")||"function"!==typeof fetch?c(b):fetch(K,{credentials:"same-origin"}).then(function(e){return WebAssembly.instantiateStreaming(e,
d).then(b,function(f){B("wasm streaming compile failed: "+f);B("falling back to ArrayBuffer instantiation");return c(b)})})})().catch(ba);return{}})();h.___wasm_call_ctors=function(){return(h.___wasm_call_ctors=h.asm.F).apply(null,arguments)};var mc=h._malloc=function(){return(mc=h._malloc=h.asm.G).apply(null,arguments)},Kb=h.___getTypeName=function(){return(Kb=h.___getTypeName=h.asm.I).apply(null,arguments)};
h.___embind_register_native_and_builtin_types=function(){return(h.___embind_register_native_and_builtin_types=h.asm.J).apply(null,arguments)};var S=h._free=function(){return(S=h._free=h.asm.K).apply(null,arguments)};h.dynCall_viijii=function(){return(h.dynCall_viijii=h.asm.L).apply(null,arguments)};h.dynCall_jiji=function(){return(h.dynCall_jiji=h.asm.M).apply(null,arguments)};h.dynCall_iiiiij=function(){return(h.dynCall_iiiiij=h.asm.N).apply(null,arguments)};
h.dynCall_iiiiijj=function(){return(h.dynCall_iiiiijj=h.asm.O).apply(null,arguments)};h.dynCall_iiiiiijj=function(){return(h.dynCall_iiiiiijj=h.asm.P).apply(null,arguments)};var ad;Na=function bd(){ad||cd();ad||(Na=bd)};
function cd(){function a(){if(!ad&&(ad=!0,h.calledRun=!0,!sa)){h.noFSInit||Mc||(Mc=!0,Lc(),h.stdin=h.stdin,h.stdout=h.stdout,h.stderr=h.stderr,h.stdin?Oc("stdin",h.stdin):Hc("/dev/tty","/dev/stdin"),h.stdout?Oc("stdout",null,h.stdout):Hc("/dev/tty","/dev/stdout"),h.stderr?Oc("stderr",null,h.stderr):Hc("/dev/tty1","/dev/stderr"),Ic("/dev/stdin",0),Ic("/dev/stdout",1),Ic("/dev/stderr",1));Ua(Ja);aa(h);if(h.onRuntimeInitialized)h.onRuntimeInitialized();if(h.postRun)for("function"==typeof h.postRun&&
(h.postRun=[h.postRun]);h.postRun.length;){var b=h.postRun.shift();Ka.unshift(b)}Ua(Ka)}}if(!(0<J)){if(h.preRun)for("function"==typeof h.preRun&&(h.preRun=[h.preRun]);h.preRun.length;)La();Ua(Ia);0<J||(h.setStatus?(h.setStatus("Running..."),setTimeout(function(){setTimeout(function(){h.setStatus("")},1);a()},1)):a())}}h.run=cd;if(h.preInit)for("function"==typeof h.preInit&&(h.preInit=[h.preInit]);0<h.preInit.length;)h.preInit.pop()();cd();


  return Module.ready
}
);
})();
if (typeof exports === 'object' && typeof module === 'object')
  module.exports = Module;
else if (typeof define === 'function' && define['amd'])
  define([], function() { return Module; });
else if (typeof exports === 'object')
  exports["Module"] = Module;
