
var Module = (function() {
  var _scriptDir = typeof document !== 'undefined' && document.currentScript ? document.currentScript.src : undefined;
  if (typeof __filename !== 'undefined') _scriptDir = _scriptDir || __filename;
  return (
function(Module) {
  Module = Module || {};


var f;f||(f=typeof Module !== 'undefined' ? Module : {});var aa;f.ready=new Promise(function(a){aa=a});var ba={},r;for(r in f)f.hasOwnProperty(r)&&(ba[r]=f[r]);var ca="./this.program",da=!1,u=!1,ea=!1,fa=!1;da="object"===typeof window;u="function"===typeof importScripts;ea="object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node;fa=!da&&!ea&&!u;var y="",ja,ka,la,ma;
if(ea)y=u?require("path").dirname(y)+"/":__dirname+"/",ja=function(a,b){la||(la=require("fs"));ma||(ma=require("path"));a=ma.normalize(a);return la.readFileSync(a,b?null:"utf8")},ka=function(a){a=ja(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a},1<process.argv.length&&(ca=process.argv[1].replace(/\\/g,"/")),process.argv.slice(2),process.on("uncaughtException",function(a){throw a;}),process.on("unhandledRejection",z),f.inspect=function(){return"[Emscripten Module object]"};else if(fa)"undefined"!=
typeof read&&(ja=function(a){return read(a)}),ka=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");assert("object"===typeof a);return a},"undefined"!==typeof print&&("undefined"===typeof console&&(console={}),console.log=print,console.warn=console.error="undefined"!==typeof printErr?printErr:print);else if(da||u)u?y=self.location.href:document.currentScript&&(y=document.currentScript.src),_scriptDir&&(y=_scriptDir),0!==y.indexOf("blob:")?y=y.substr(0,
y.lastIndexOf("/")+1):y="",ja=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},u&&(ka=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});var na=f.print||console.log.bind(console),B=f.printErr||console.warn.bind(console);for(r in ba)ba.hasOwnProperty(r)&&(f[r]=ba[r]);ba=null;f.thisProgram&&(ca=f.thisProgram);var oa;f.wasmBinary&&(oa=f.wasmBinary);var noExitRuntime;
f.noExitRuntime&&(noExitRuntime=f.noExitRuntime);"object"!==typeof WebAssembly&&B("no native wasm support detected");var pa,qa=new WebAssembly.Table({initial:481,maximum:481,element:"anyfunc"}),ra=!1;function assert(a,b){a||z("Assertion failed: "+b)}var sa="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function C(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.subarray&&sa)return sa.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var g=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|g);else{var k=a[b++]&63;e=224==(e&240)?(e&15)<<12|g<<6|k:(e&7)<<18|g<<12|k<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d}
function ta(a,b,c,d){if(!(0<d))return 0;var e=c;d=c+d-1;for(var g=0;g<a.length;++g){var k=a.charCodeAt(g);if(55296<=k&&57343>=k){var l=a.charCodeAt(++g);k=65536+((k&1023)<<10)|l&1023}if(127>=k){if(c>=d)break;b[c++]=k}else{if(2047>=k){if(c+1>=d)break;b[c++]=192|k>>6}else{if(65535>=k){if(c+2>=d)break;b[c++]=224|k>>12}else{if(c+3>=d)break;b[c++]=240|k>>18;b[c++]=128|k>>12&63}b[c++]=128|k>>6&63}b[c++]=128|k&63}}b[c]=0;return c-e}
function ua(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}var va="undefined"!==typeof TextDecoder?new TextDecoder("utf-16le"):void 0;function wa(a,b){var c=a>>1;for(var d=c+b/2;!(c>=d)&&xa[c];)++c;c<<=1;if(32<c-a&&va)return va.decode(E.subarray(a,c));c=0;for(d="";;){var e=ya[a+2*c>>1];if(0==e||c==b/2)return d;++c;d+=String.fromCharCode(e)}}
function za(a,b,c){void 0===c&&(c=2147483647);if(2>c)return 0;c-=2;var d=b;c=c<2*a.length?c/2:a.length;for(var e=0;e<c;++e)ya[b>>1]=a.charCodeAt(e),b+=2;ya[b>>1]=0;return b-d}function Aa(a){return 2*a.length}function Ba(a,b){for(var c=0,d="";!(c>=b/4);){var e=F[a+4*c>>2];if(0==e)break;++c;65536<=e?(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023)):d+=String.fromCharCode(e)}return d}
function Ca(a,b,c){void 0===c&&(c=2147483647);if(4>c)return 0;var d=b;c=d+c-4;for(var e=0;e<a.length;++e){var g=a.charCodeAt(e);if(55296<=g&&57343>=g){var k=a.charCodeAt(++e);g=65536+((g&1023)<<10)|k&1023}F[b>>2]=g;b+=4;if(b+4>c)break}F[b>>2]=0;return b-d}function Da(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&++c;b+=4}return b}var Ea,G,E,ya,xa,F,H,Fa,Ga,Ha=f.INITIAL_MEMORY||16777216;
f.wasmMemory?pa=f.wasmMemory:pa=new WebAssembly.Memory({initial:Ha/65536,maximum:Ha/65536});pa&&(Ea=pa.buffer);Ha=Ea.byteLength;var I=Ea;Ea=I;f.HEAP8=G=new Int8Array(I);f.HEAP16=ya=new Int16Array(I);f.HEAP32=F=new Int32Array(I);f.HEAPU8=E=new Uint8Array(I);f.HEAPU16=xa=new Uint16Array(I);f.HEAPU32=H=new Uint32Array(I);f.HEAPF32=Fa=new Float32Array(I);f.HEAPF64=Ga=new Float64Array(I);F[7208]=5271872;
function Ia(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(f);else{var c=b.lb;"number"===typeof c?void 0===b.Oa?f.dynCall_v(c):f.dynCall_vi(c,b.Oa):c(void 0===b.Oa?null:b.Oa)}}}var Ja=[],Ka=[],La=[],Ma=[];function Na(){var a=f.preRun.shift();Ja.unshift(a)}var J=0,Oa=null,Pa=null;f.preloadedImages={};f.preloadedAudios={};function z(a){if(f.onAbort)f.onAbort(a);na(a);B(a);ra=!0;throw new WebAssembly.RuntimeError("abort("+a+"). Build with -s ASSERTIONS=1 for more info.");}
function Qa(a){var b=K;return String.prototype.startsWith?b.startsWith(a):0===b.indexOf(a)}function Ra(){return Qa("data:application/octet-stream;base64,")}var K="chess-wasm.wasm";if(!Ra()){var Sa=K;K=f.locateFile?f.locateFile(Sa,y):y+Sa}function Ta(){try{if(oa)return new Uint8Array(oa);if(ka)return ka(K);throw"both async and sync fetching of the wasm failed";}catch(a){z(a)}}
function Ua(){return oa||!da&&!u||"function"!==typeof fetch||Qa("file://")?new Promise(function(a){a(Ta())}):fetch(K,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+K+"'";return a.arrayBuffer()}).catch(function(){return Ta()})}Ka.push({lb:function(){Va()}});function Wa(){return 0<Wa.Ea}
function Xa(a,b){for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a}function Ya(a){var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=Xa(a.split("/").filter(function(d){return!!d}),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a}
function Za(a){var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b}function $a(a){if("/"===a)return"/";var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)}
function ab(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!==typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=Xa(a.split("/").filter(function(d){return!!d}),!b).join("/");return(b?"/":"")+a||"."}var bb=[];function cb(a,b){bb[a]={input:[],output:[],ya:b};db(a,eb)}
var eb={open:function(a){var b=bb[a.node.rdev];if(!b)throw new L(43);a.tty=b;a.seekable=!1},close:function(a){a.tty.ya.flush(a.tty)},flush:function(a){a.tty.ya.flush(a.tty)},read:function(a,b,c,d){if(!a.tty||!a.tty.ya.ab)throw new L(60);for(var e=0,g=0;g<d;g++){try{var k=a.tty.ya.ab(a.tty)}catch(l){throw new L(29);}if(void 0===k&&0===e)throw new L(6);if(null===k||void 0===k)break;e++;b[c+g]=k}e&&(a.node.timestamp=Date.now());return e},write:function(a,b,c,d){if(!a.tty||!a.tty.ya.Qa)throw new L(60);
try{for(var e=0;e<d;e++)a.tty.ya.Qa(a.tty,b[c+e])}catch(g){throw new L(29);}d&&(a.node.timestamp=Date.now());return e}},gb={ab:function(a){if(!a.input.length){var b=null;if(ea){var c=Buffer.Ea?Buffer.Ea(256):new Buffer(256),d=0;try{d=la.readSync(process.stdin.fd,c,0,256,null)}catch(e){if(-1!=e.toString().indexOf("EOF"))d=0;else throw e;}0<d?b=c.slice(0,d).toString("utf-8"):b=null}else"undefined"!=typeof window&&"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==
typeof readline&&(b=readline(),null!==b&&(b+="\n"));if(!b)return null;a.input=fb(b,!0)}return a.input.shift()},Qa:function(a,b){null===b||10===b?(na(C(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(na(C(a.output,0)),a.output=[])}},hb={Qa:function(a,b){null===b||10===b?(B(C(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(B(C(a.output,0)),a.output=[])}},M={oa:null,ra:function(){return M.createNode(null,
"/",16895,0)},createNode:function(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new L(63);M.oa||(M.oa={dir:{node:{ta:M.da.ta,qa:M.da.qa,lookup:M.da.lookup,Ia:M.da.Ia,rename:M.da.rename,unlink:M.da.unlink,rmdir:M.da.rmdir,readdir:M.da.readdir,symlink:M.da.symlink},stream:{Aa:M.ga.Aa}},file:{node:{ta:M.da.ta,qa:M.da.qa},stream:{Aa:M.ga.Aa,read:M.ga.read,write:M.ga.write,Ua:M.ga.Ua,bb:M.ga.bb,Ka:M.ga.Ka}},link:{node:{ta:M.da.ta,qa:M.da.qa,readlink:M.da.readlink},stream:{}},Va:{node:{ta:M.da.ta,
qa:M.da.qa},stream:ib}});c=jb(a,b,c,d);16384===(c.mode&61440)?(c.da=M.oa.dir.node,c.ga=M.oa.dir.stream,c.ba={}):32768===(c.mode&61440)?(c.da=M.oa.file.node,c.ga=M.oa.file.stream,c.ha=0,c.ba=null):40960===(c.mode&61440)?(c.da=M.oa.link.node,c.ga=M.oa.link.stream):8192===(c.mode&61440)&&(c.da=M.oa.Va.node,c.ga=M.oa.Va.stream);c.timestamp=Date.now();a&&(a.ba[b]=c);return c},Hb:function(a){if(a.ba&&a.ba.subarray){for(var b=[],c=0;c<a.ha;++c)b.push(a.ba[c]);return b}return a.ba},Ib:function(a){return a.ba?
a.ba.subarray?a.ba.subarray(0,a.ha):new Uint8Array(a.ba):new Uint8Array(0)},Xa:function(a,b){var c=a.ba?a.ba.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),c=a.ba,a.ba=new Uint8Array(b),0<a.ha&&a.ba.set(c.subarray(0,a.ha),0))},xb:function(a,b){if(a.ha!=b)if(0==b)a.ba=null,a.ha=0;else{if(!a.ba||a.ba.subarray){var c=a.ba;a.ba=new Uint8Array(b);c&&a.ba.set(c.subarray(0,Math.min(b,a.ha)))}else if(a.ba||(a.ba=[]),a.ba.length>b)a.ba.length=b;else for(;a.ba.length<b;)a.ba.push(0);
a.ha=b}},da:{ta:function(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;16384===(a.mode&61440)?b.size=4096:32768===(a.mode&61440)?b.size=a.ha:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.atime=new Date(a.timestamp);b.mtime=new Date(a.timestamp);b.ctime=new Date(a.timestamp);b.gb=4096;b.blocks=Math.ceil(b.size/b.gb);return b},qa:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==
b.size&&M.xb(a,b.size)},lookup:function(){throw kb[44];},Ia:function(a,b,c,d){return M.createNode(a,b,c,d)},rename:function(a,b,c){if(16384===(a.mode&61440)){try{var d=lb(b,c)}catch(g){}if(d)for(var e in d.ba)throw new L(55);}delete a.parent.ba[a.name];a.name=c;b.ba[c]=a;a.parent=b},unlink:function(a,b){delete a.ba[b]},rmdir:function(a,b){var c=lb(a,b),d;for(d in c.ba)throw new L(55);delete a.ba[b]},readdir:function(a){var b=[".",".."],c;for(c in a.ba)a.ba.hasOwnProperty(c)&&b.push(c);return b},symlink:function(a,
b,c){a=M.createNode(a,b,41471,0);a.link=c;return a},readlink:function(a){if(40960!==(a.mode&61440))throw new L(28);return a.link}},ga:{read:function(a,b,c,d,e){var g=a.node.ba;if(e>=a.node.ha)return 0;a=Math.min(a.node.ha-e,d);if(8<a&&g.subarray)b.set(g.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=g[e+d];return a},write:function(a,b,c,d,e,g){if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.ba||a.ba.subarray)){if(g)return a.ba=b.subarray(c,c+d),a.ha=d;if(0===a.ha&&0===e)return a.ba=
b.slice(c,c+d),a.ha=d;if(e+d<=a.ha)return a.ba.set(b.subarray(c,c+d),e),d}M.Xa(a,e+d);if(a.ba.subarray&&b.subarray)a.ba.set(b.subarray(c,c+d),e);else for(g=0;g<d;g++)a.ba[e+g]=b[c+g];a.ha=Math.max(a.ha,e+d);return d},Aa:function(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.ha);if(0>b)throw new L(28);return b},Ua:function(a,b,c){M.Xa(a.node,b+c);a.node.ha=Math.max(a.node.ha,b+c)},bb:function(a,b,c,d,e,g){assert(0===b);if(32768!==(a.node.mode&61440))throw new L(43);a=a.node.ba;
if(g&2||a.buffer!==Ea){if(0<d||d+c<a.length)a.subarray?a=a.subarray(d,d+c):a=Array.prototype.slice.call(a,d,d+c);d=!0;c=mb(c);if(!c)throw new L(48);G.set(a,c)}else d=!1,c=a.byteOffset;return{fa:c,fb:d}},Ka:function(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new L(43);if(e&2)return 0;M.ga.write(a,b,0,d,c,!1);return 0}}},nb=null,ob={},pb=[],qb=1,rb=null,sb=!0,tb={},L=null,kb={};
function N(a,b){a=ab("/",a);b=b||{};if(!a)return{path:"",node:null};var c={$a:!0,Sa:0},d;for(d in c)void 0===b[d]&&(b[d]=c[d]);if(8<b.Sa)throw new L(32);a=Xa(a.split("/").filter(function(k){return!!k}),!1);var e=nb;c="/";for(d=0;d<a.length;d++){var g=d===a.length-1;if(g&&b.parent)break;e=lb(e,a[d]);c=Ya(c+"/"+a[d]);e.Ja&&(!g||g&&b.$a)&&(e=e.Ja.root);if(!g||b.Za)for(g=0;40960===(e.mode&61440);)if(e=ub(c),c=ab(Za(c),e),e=N(c,{Sa:b.Sa}).node,40<g++)throw new L(32);}return{path:c,node:e}}
function vb(a){for(var b;;){if(a===a.parent)return a=a.ra.cb,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}}function wb(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%rb.length}function lb(a,b){var c;if(c=(c=xb(a,"x"))?c:a.da.lookup?0:2)throw new L(c,a);for(c=rb[wb(a.id,b)];c;c=c.tb){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.da.lookup(a,b)}
function jb(a,b,c,d){a=new yb(a,b,c,d);b=wb(a.parent.id,a.name);a.tb=rb[b];return rb[b]=a}var zb={r:0,rs:1052672,"r+":2,w:577,wx:705,xw:705,"w+":578,"wx+":706,"xw+":706,a:1089,ax:1217,xa:1217,"a+":1090,"ax+":1218,"xa+":1218};function Ab(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}function xb(a,b){if(sb)return 0;if(-1===b.indexOf("r")||a.mode&292){if(-1!==b.indexOf("w")&&!(a.mode&146)||-1!==b.indexOf("x")&&!(a.mode&73))return 2}else return 2;return 0}
function Bb(a,b){try{return lb(a,b),20}catch(c){}return xb(a,"wx")}function Cb(){var a=4096;for(var b=0;b<=a;b++)if(!pb[b])return b;throw new L(33);}function Db(a){Eb||(Eb=function(){},Eb.prototype={});var b=new Eb,c;for(c in a)b[c]=a[c];a=b;b=Cb();a.fd=b;return pb[b]=a}var ib={open:function(a){a.ga=ob[a.node.rdev].ga;a.ga.open&&a.ga.open(a)},Aa:function(){throw new L(70);}};function db(a,b){ob[a]={ga:b}}
function Fb(a,b){var c="/"===b,d=!b;if(c&&nb)throw new L(10);if(!c&&!d){var e=N(b,{$a:!1});b=e.path;e=e.node;if(e.Ja)throw new L(10);if(16384!==(e.mode&61440))throw new L(54);}b={type:a,Mb:{},cb:b,sb:[]};a=a.ra(b);a.ra=b;b.root=a;c?nb=a:e&&(e.Ja=b,e.ra&&e.ra.sb.push(b))}function Gb(a,b,c){var d=N(a,{parent:!0}).node;a=$a(a);if(!a||"."===a||".."===a)throw new L(28);var e=Bb(d,a);if(e)throw new L(e);if(!d.da.Ia)throw new L(63);return d.da.Ia(d,a,b,c)}function O(a){Gb(a,16895,0)}
function Hb(a,b,c){"undefined"===typeof c&&(c=b,b=438);Gb(a,b|8192,c)}function Ib(a,b){if(!ab(a))throw new L(44);var c=N(b,{parent:!0}).node;if(!c)throw new L(44);b=$a(b);var d=Bb(c,b);if(d)throw new L(d);if(!c.da.symlink)throw new L(63);c.da.symlink(c,b,a)}function ub(a){a=N(a).node;if(!a)throw new L(44);if(!a.da.readlink)throw new L(28);return ab(vb(a.parent),a.da.readlink(a))}
function Jb(a,b){if(""===a)throw new L(44);if("string"===typeof b){var c=zb[b];if("undefined"===typeof c)throw Error("Unknown file open mode: "+b);b=c}var d=b&64?("undefined"===typeof d?438:d)&4095|32768:0;if("object"===typeof a)var e=a;else{a=Ya(a);try{e=N(a,{Za:!(b&131072)}).node}catch(k){}}c=!1;if(b&64)if(e){if(b&128)throw new L(20);}else e=Gb(a,d,0),c=!0;if(!e)throw new L(44);8192===(e.mode&61440)&&(b&=-513);if(b&65536&&16384!==(e.mode&61440))throw new L(54);if(!c&&(d=e?40960===(e.mode&61440)?
32:16384===(e.mode&61440)&&("r"!==Ab(b)||b&512)?31:xb(e,Ab(b)):44))throw new L(d);if(b&512){d=e;var g;"string"===typeof d?g=N(d,{Za:!0}).node:g=d;if(!g.da.qa)throw new L(63);if(16384===(g.mode&61440))throw new L(31);if(32768!==(g.mode&61440))throw new L(28);if(d=xb(g,"w"))throw new L(d);g.da.qa(g,{size:0,timestamp:Date.now()})}b&=-131713;e=Db({node:e,path:vb(e),flags:b,seekable:!0,position:0,ga:e.ga,Pb:[],error:!1});e.ga.open&&e.ga.open(e);!f.logReadFiles||b&1||(Kb||(Kb={}),a in Kb||(Kb[a]=1,B("FS.trackingDelegate error on read file: "+
a)));try{tb.onOpenFile&&(e=0,1!==(b&2097155)&&(e|=1),0!==(b&2097155)&&(e|=2),tb.onOpenFile(a,e))}catch(k){B("FS.trackingDelegate['onOpenFile']('"+a+"', flags) threw an exception: "+k.message)}}function Lb(){L||(L=function(a,b){this.node=b;this.yb=function(c){this.jb=c};this.yb(a);this.message="FS error"},L.prototype=Error(),L.prototype.constructor=L,[44].forEach(function(a){kb[a]=new L(a);kb[a].stack="<generic error, no stack>"}))}var Mb;function Nb(a,b){var c=0;a&&(c|=365);b&&(c|=146);return c}
function Ob(a,b,c){a=Ya("/dev/"+a);var d=Nb(!!b,!!c);Pb||(Pb=64);var e=Pb++<<8|0;db(e,{open:function(g){g.seekable=!1},close:function(){c&&c.buffer&&c.buffer.length&&c(10)},read:function(g,k,l,n){for(var m=0,q=0;q<n;q++){try{var w=b()}catch(x){throw new L(29);}if(void 0===w&&0===m)throw new L(6);if(null===w||void 0===w)break;m++;k[l+q]=w}m&&(g.node.timestamp=Date.now());return m},write:function(g,k,l,n){for(var m=0;m<n;m++)try{c(k[l+m])}catch(q){throw new L(29);}n&&(g.node.timestamp=Date.now());return m}});
Hb(a,d,e)}var Pb,Qb={},Eb,Kb,Rb={},Sb={};function Tb(a){for(;a.length;){var b=a.pop();a.pop()(b)}}function Ub(a){return this.fromWireType(H[a>>2])}var Vb={},P={},Wb={};function Xb(a){if(void 0===a)return"_unknown";a=a.replace(/[^a-zA-Z0-9_]/g,"$");var b=a.charCodeAt(0);return 48<=b&&57>=b?"_"+a:a}function Yb(a,b){a=Xb(a);return(new Function("body","return function "+a+'() {\n    "use strict";    return body.apply(this, arguments);\n};\n'))(b)}
function Zb(a){var b=Error,c=Yb(a,function(d){this.name=a;this.message=d;d=Error(d).stack;void 0!==d&&(this.stack=this.toString()+"\n"+d.replace(/^Error(:[^\n]*)?\n/,""))});c.prototype=Object.create(b.prototype);c.prototype.constructor=c;c.prototype.toString=function(){return void 0===this.message?this.name:this.name+": "+this.message};return c}var $b=void 0;function ac(a){throw new $b(a);}
function bc(a,b,c){function d(l){l=c(l);l.length!==a.length&&ac("Mismatched type converter count");for(var n=0;n<a.length;++n)Q(a[n],l[n])}a.forEach(function(l){Wb[l]=b});var e=Array(b.length),g=[],k=0;b.forEach(function(l,n){P.hasOwnProperty(l)?e[n]=P[l]:(g.push(l),Vb.hasOwnProperty(l)||(Vb[l]=[]),Vb[l].push(function(){e[n]=P[l];++k;k===g.length&&d(e)}))});0===g.length&&d(e)}
function cc(a){switch(a){case 1:return 0;case 2:return 1;case 4:return 2;case 8:return 3;default:throw new TypeError("Unknown type size: "+a);}}var dc=void 0;function R(a){for(var b="";E[a];)b+=dc[E[a++]];return b}var ec=void 0;function S(a){throw new ec(a);}
function Q(a,b,c){c=c||{};if(!("argPackAdvance"in b))throw new TypeError("registerType registeredInstance requires argPackAdvance");var d=b.name;a||S('type "'+d+'" must have a positive integer typeid pointer');if(P.hasOwnProperty(a)){if(c.rb)return;S("Cannot register type '"+d+"' twice")}P[a]=b;delete Wb[a];Vb.hasOwnProperty(a)&&(b=Vb[a],delete Vb[a],b.forEach(function(e){e()}))}function fc(a){return{count:a.count,va:a.va,Ba:a.Ba,fa:a.fa,ia:a.ia,ka:a.ka,la:a.la}}
function hc(a){S(a.aa.ia.ea.name+" instance already deleted")}var ic=!1;function jc(){}function kc(a){--a.count.value;0===a.count.value&&(a.ka?a.la.sa(a.ka):a.ia.ea.sa(a.fa))}
function lc(a){if("undefined"===typeof FinalizationGroup)return lc=function(b){return b},a;ic=new FinalizationGroup(function(b){for(var c=b.next();!c.done;c=b.next())c=c.value,c.fa?kc(c):console.warn("object already deleted: "+c.fa)});lc=function(b){ic.register(b,b.aa,b.aa);return b};jc=function(b){ic.unregister(b.aa)};return lc(a)}var mc=void 0,nc=[];function oc(){for(;nc.length;){var a=nc.pop();a.aa.va=!1;a["delete"]()}}function T(){}var pc={};
function qc(a,b,c){if(void 0===a[b].pa){var d=a[b];a[b]=function(){a[b].pa.hasOwnProperty(arguments.length)||S("Function '"+c+"' called with an invalid number of arguments ("+arguments.length+") - expects one of ("+a[b].pa+")!");return a[b].pa[arguments.length].apply(this,arguments)};a[b].pa=[];a[b].pa[d.Fa]=d}}
function rc(a,b){f.hasOwnProperty(a)?(S("Cannot register public name '"+a+"' twice"),qc(f,a,a),f.hasOwnProperty(void 0)&&S("Cannot register multiple overloads of a function with the same number of arguments (undefined)!"),f[a].pa[void 0]=b):f[a]=b}function sc(a,b,c,d,e,g,k,l){this.name=a;this.constructor=b;this.wa=c;this.sa=d;this.ma=e;this.mb=g;this.Da=k;this.ib=l;this.vb=[]}
function tc(a,b,c){for(;b!==c;)b.Da||S("Expected null or instance of "+c.name+", got an instance of "+b.name),a=b.Da(a),b=b.ma;return a}function wc(a,b){if(null===b)return this.Pa&&S("null is not a valid "+this.name),0;b.aa||S('Cannot pass "'+xc(b)+'" as a '+this.name);b.aa.fa||S("Cannot pass deleted object as a pointer of type "+this.name);return tc(b.aa.fa,b.aa.ia.ea,this.ea)}
function yc(a,b){if(null===b){this.Pa&&S("null is not a valid "+this.name);if(this.Ha){var c=this.Ra();null!==a&&a.push(this.sa,c);return c}return 0}b.aa||S('Cannot pass "'+xc(b)+'" as a '+this.name);b.aa.fa||S("Cannot pass deleted object as a pointer of type "+this.name);!this.Ga&&b.aa.ia.Ga&&S("Cannot convert argument of type "+(b.aa.la?b.aa.la.name:b.aa.ia.name)+" to parameter type "+this.name);c=tc(b.aa.fa,b.aa.ia.ea,this.ea);if(this.Ha)switch(void 0===b.aa.ka&&S("Passing raw pointer to smart pointer is illegal"),
this.Cb){case 0:b.aa.la===this?c=b.aa.ka:S("Cannot convert argument of type "+(b.aa.la?b.aa.la.name:b.aa.ia.name)+" to parameter type "+this.name);break;case 1:c=b.aa.ka;break;case 2:if(b.aa.la===this)c=b.aa.ka;else{var d=b.clone();c=this.wb(c,zc(function(){d["delete"]()}));null!==a&&a.push(this.sa,c)}break;default:S("Unsupporting sharing policy")}return c}
function Ac(a,b){if(null===b)return this.Pa&&S("null is not a valid "+this.name),0;b.aa||S('Cannot pass "'+xc(b)+'" as a '+this.name);b.aa.fa||S("Cannot pass deleted object as a pointer of type "+this.name);b.aa.ia.Ga&&S("Cannot convert argument of type "+b.aa.ia.name+" to parameter type "+this.name);return tc(b.aa.fa,b.aa.ia.ea,this.ea)}function Bc(a,b,c){if(b===c)return a;if(void 0===c.ma)return null;a=Bc(a,b,c.ma);return null===a?null:c.ib(a)}var Cc={};
function Dc(a,b){for(void 0===b&&S("ptr should not be undefined");a.ma;)b=a.Da(b),a=a.ma;return Cc[b]}function Ec(a,b){b.ia&&b.fa||ac("makeClassHandle requires ptr and ptrType");!!b.la!==!!b.ka&&ac("Both smartPtrType and smartPtr must be specified");b.count={value:1};return lc(Object.create(a,{aa:{value:b}}))}
function U(a,b,c,d){this.name=a;this.ea=b;this.Pa=c;this.Ga=d;this.Ha=!1;this.sa=this.wb=this.Ra=this.eb=this.Cb=this.ub=void 0;void 0!==b.ma?this.toWireType=yc:(this.toWireType=d?wc:Ac,this.na=null)}function Fc(a,b){f.hasOwnProperty(a)||ac("Replacing nonexistant public symbol");f[a]=b;f[a].Fa=void 0}
function V(a,b){a=R(a);var c=f["dynCall_"+a];for(var d=[],e=1;e<a.length;++e)d.push("a"+e);e="return function dynCall_"+(a+"_"+b)+"("+d.join(", ")+") {\n";e+="    return dynCall(rawFunction"+(d.length?", ":"")+d.join(", ")+");\n";c=(new Function("dynCall","rawFunction",e+"};\n"))(c,b);"function"!==typeof c&&S("unknown function pointer with signature "+a+": "+b);return c}var Gc=void 0;function Hc(a){a=Ic(a);var b=R(a);W(a);return b}
function Jc(a,b){function c(g){e[g]||P[g]||(Wb[g]?Wb[g].forEach(c):(d.push(g),e[g]=!0))}var d=[],e={};b.forEach(c);throw new Gc(a+": "+d.map(Hc).join([", "]));}function Kc(a,b){for(var c=[],d=0;d<a;d++)c.push(F[(b>>2)+d]);return c}
function Lc(a){var b=Function;if(!(b instanceof Function))throw new TypeError("new_ called with constructor type "+typeof b+" which is not a function");var c=Yb(b.name||"unknownFunctionName",function(){});c.prototype=b.prototype;c=new c;a=b.apply(c,a);return a instanceof Object?a:c}var Mc=[],X=[{},{value:void 0},{value:null},{value:!0},{value:!1}];function Nc(a){4<a&&0===--X[a].Ta&&(X[a]=void 0,Mc.push(a))}
function zc(a){switch(a){case void 0:return 1;case null:return 2;case !0:return 3;case !1:return 4;default:var b=Mc.length?Mc.pop():X.length;X[b]={Ta:1,value:a};return b}}function xc(a){if(null===a)return"null";var b=typeof a;return"object"===b||"array"===b||"function"===b?a.toString():""+a}function Oc(a,b){switch(b){case 2:return function(c){return this.fromWireType(Fa[c>>2])};case 3:return function(c){return this.fromWireType(Ga[c>>3])};default:throw new TypeError("Unknown float type: "+a);}}
function Pc(a,b,c){switch(b){case 0:return c?function(d){return G[d]}:function(d){return E[d]};case 1:return c?function(d){return ya[d>>1]}:function(d){return xa[d>>1]};case 2:return c?function(d){return F[d>>2]}:function(d){return H[d>>2]};default:throw new TypeError("Unknown integer type: "+a);}}var Qc={};
function Rc(){if(!Sc){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"===typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:ca||"./this.program"},b;for(b in Qc)a[b]=Qc[b];var c=[];for(b in a)c.push(b+"="+a[b]);Sc=c}return Sc}var Sc;function Tc(a){return 0===a%4&&(0!==a%100||0===a%400)}function Uc(a,b){for(var c=0,d=0;d<=b;c+=a[d++]);return c}
var Vc=[31,29,31,30,31,30,31,31,30,31,30,31],Wc=[31,28,31,30,31,30,31,31,30,31,30,31];function Xc(a,b){for(a=new Date(a.getTime());0<b;){var c=a.getMonth(),d=(Tc(a.getFullYear())?Vc:Wc)[c];if(b>d-a.getDate())b-=d-a.getDate()+1,a.setDate(1),11>c?a.setMonth(c+1):(a.setMonth(0),a.setFullYear(a.getFullYear()+1));else{a.setDate(a.getDate()+b);break}}return a}
function Yc(a,b,c,d){function e(h,p,v){for(h="number"===typeof h?h.toString():h||"";h.length<p;)h=v[0]+h;return h}function g(h,p){return e(h,p,"0")}function k(h,p){function v(D){return 0>D?-1:0<D?1:0}var t;0===(t=v(h.getFullYear()-p.getFullYear()))&&0===(t=v(h.getMonth()-p.getMonth()))&&(t=v(h.getDate()-p.getDate()));return t}function l(h){switch(h.getDay()){case 0:return new Date(h.getFullYear()-1,11,29);case 1:return h;case 2:return new Date(h.getFullYear(),0,3);case 3:return new Date(h.getFullYear(),
0,2);case 4:return new Date(h.getFullYear(),0,1);case 5:return new Date(h.getFullYear()-1,11,31);case 6:return new Date(h.getFullYear()-1,11,30)}}function n(h){h=Xc(new Date(h.ja+1900,0,1),h.Na);var p=new Date(h.getFullYear()+1,0,4),v=l(new Date(h.getFullYear(),0,4));p=l(p);return 0>=k(v,h)?0>=k(p,h)?h.getFullYear()+1:h.getFullYear():h.getFullYear()-1}var m=F[d+40>>2];d={Fb:F[d>>2],Eb:F[d+4>>2],La:F[d+8>>2],Ca:F[d+12>>2],za:F[d+16>>2],ja:F[d+20>>2],Ma:F[d+24>>2],Na:F[d+28>>2],Ob:F[d+32>>2],Db:F[d+
36>>2],Gb:m?m?C(E,m,void 0):"":""};c=c?C(E,c,void 0):"";m={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S","%Ec":"%c","%EC":"%C","%Ex":"%m/%d/%y","%EX":"%H:%M:%S","%Ey":"%y","%EY":"%Y","%Od":"%d","%Oe":"%e","%OH":"%H","%OI":"%I","%Om":"%m","%OM":"%M","%OS":"%S","%Ou":"%u","%OU":"%U","%OV":"%V","%Ow":"%w","%OW":"%W","%Oy":"%y"};for(var q in m)c=c.replace(new RegExp(q,"g"),m[q]);var w="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),
x="January February March April May June July August September October November December".split(" ");m={"%a":function(h){return w[h.Ma].substring(0,3)},"%A":function(h){return w[h.Ma]},"%b":function(h){return x[h.za].substring(0,3)},"%B":function(h){return x[h.za]},"%C":function(h){return g((h.ja+1900)/100|0,2)},"%d":function(h){return g(h.Ca,2)},"%e":function(h){return e(h.Ca,2," ")},"%g":function(h){return n(h).toString().substring(2)},"%G":function(h){return n(h)},"%H":function(h){return g(h.La,
2)},"%I":function(h){h=h.La;0==h?h=12:12<h&&(h-=12);return g(h,2)},"%j":function(h){return g(h.Ca+Uc(Tc(h.ja+1900)?Vc:Wc,h.za-1),3)},"%m":function(h){return g(h.za+1,2)},"%M":function(h){return g(h.Eb,2)},"%n":function(){return"\n"},"%p":function(h){return 0<=h.La&&12>h.La?"AM":"PM"},"%S":function(h){return g(h.Fb,2)},"%t":function(){return"\t"},"%u":function(h){return h.Ma||7},"%U":function(h){var p=new Date(h.ja+1900,0,1),v=0===p.getDay()?p:Xc(p,7-p.getDay());h=new Date(h.ja+1900,h.za,h.Ca);return 0>
k(v,h)?g(Math.ceil((31-v.getDate()+(Uc(Tc(h.getFullYear())?Vc:Wc,h.getMonth()-1)-31)+h.getDate())/7),2):0===k(v,p)?"01":"00"},"%V":function(h){var p=new Date(h.ja+1901,0,4),v=l(new Date(h.ja+1900,0,4));p=l(p);var t=Xc(new Date(h.ja+1900,0,1),h.Na);return 0>k(t,v)?"53":0>=k(p,t)?"01":g(Math.ceil((v.getFullYear()<h.ja+1900?h.Na+32-v.getDate():h.Na+1-v.getDate())/7),2)},"%w":function(h){return h.Ma},"%W":function(h){var p=new Date(h.ja,0,1),v=1===p.getDay()?p:Xc(p,0===p.getDay()?1:7-p.getDay()+1);h=
new Date(h.ja+1900,h.za,h.Ca);return 0>k(v,h)?g(Math.ceil((31-v.getDate()+(Uc(Tc(h.getFullYear())?Vc:Wc,h.getMonth()-1)-31)+h.getDate())/7),2):0===k(v,p)?"01":"00"},"%y":function(h){return(h.ja+1900).toString().substring(2)},"%Y":function(h){return h.ja+1900},"%z":function(h){h=h.Db;var p=0<=h;h=Math.abs(h)/60;return(p?"+":"-")+String("0000"+(h/60*100+h%60)).slice(-4)},"%Z":function(h){return h.Gb},"%%":function(){return"%"}};for(q in m)0<=c.indexOf(q)&&(c=c.replace(new RegExp(q,"g"),m[q](d)));q=
fb(c,!1);if(q.length>b)return 0;G.set(q,a);return q.length-1}function yb(a,b,c,d){a||(a=this);this.parent=a;this.ra=a.ra;this.Ja=null;this.id=qb++;this.name=b;this.mode=c;this.da={};this.ga={};this.rdev=d}Object.defineProperties(yb.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}}});Lb();rb=Array(4096);Fb(M,"/");O("/tmp");O("/home");
O("/home/web_user");
(function(){O("/dev");db(259,{read:function(){return 0},write:function(d,e,g,k){return k}});Hb("/dev/null",259);cb(1280,gb);cb(1536,hb);Hb("/dev/tty",1280);Hb("/dev/tty1",1536);if("object"===typeof crypto&&"function"===typeof crypto.getRandomValues){var a=new Uint8Array(1);var b=function(){crypto.getRandomValues(a);return a[0]}}else if(ea)try{var c=require("crypto");b=function(){return c.randomBytes(1)[0]}}catch(d){}b||(b=function(){z("random_device")});Ob("random",b);Ob("urandom",b);O("/dev/shm");
O("/dev/shm/tmp")})();O("/proc");O("/proc/self");O("/proc/self/fd");Fb({ra:function(){var a=jb("/proc/self","fd",16895,73);a.da={lookup:function(b,c){var d=pb[+c];if(!d)throw new L(8);b={parent:null,ra:{cb:"fake"},da:{readlink:function(){return d.path}}};return b.parent=b}};return a}},"/proc/self/fd");$b=f.InternalError=Zb("InternalError");for(var Zc=Array(256),$c=0;256>$c;++$c)Zc[$c]=String.fromCharCode($c);dc=Zc;ec=f.BindingError=Zb("BindingError");
T.prototype.isAliasOf=function(a){if(!(this instanceof T&&a instanceof T))return!1;var b=this.aa.ia.ea,c=this.aa.fa,d=a.aa.ia.ea;for(a=a.aa.fa;b.ma;)c=b.Da(c),b=b.ma;for(;d.ma;)a=d.Da(a),d=d.ma;return b===d&&c===a};T.prototype.clone=function(){this.aa.fa||hc(this);if(this.aa.Ba)return this.aa.count.value+=1,this;var a=lc(Object.create(Object.getPrototypeOf(this),{aa:{value:fc(this.aa)}}));a.aa.count.value+=1;a.aa.va=!1;return a};
T.prototype["delete"]=function(){this.aa.fa||hc(this);this.aa.va&&!this.aa.Ba&&S("Object already scheduled for deletion");jc(this);kc(this.aa);this.aa.Ba||(this.aa.ka=void 0,this.aa.fa=void 0)};T.prototype.isDeleted=function(){return!this.aa.fa};T.prototype.deleteLater=function(){this.aa.fa||hc(this);this.aa.va&&!this.aa.Ba&&S("Object already scheduled for deletion");nc.push(this);1===nc.length&&mc&&mc(oc);this.aa.va=!0;return this};U.prototype.nb=function(a){this.eb&&(a=this.eb(a));return a};
U.prototype.Wa=function(a){this.sa&&this.sa(a)};U.prototype.argPackAdvance=8;U.prototype.readValueFromPointer=Ub;U.prototype.deleteObject=function(a){if(null!==a)a["delete"]()};
U.prototype.fromWireType=function(a){function b(){return this.Ha?Ec(this.ea.wa,{ia:this.ub,fa:c,la:this,ka:a}):Ec(this.ea.wa,{ia:this,fa:a})}var c=this.nb(a);if(!c)return this.Wa(a),null;var d=Dc(this.ea,c);if(void 0!==d){if(0===d.aa.count.value)return d.aa.fa=c,d.aa.ka=a,d.clone();d=d.clone();this.Wa(a);return d}d=this.ea.mb(c);d=pc[d];if(!d)return b.call(this);d=this.Ga?d.hb:d.pointerType;var e=Bc(c,this.ea,d.ea);return null===e?b.call(this):this.Ha?Ec(d.ea.wa,{ia:d,fa:e,la:this,ka:a}):Ec(d.ea.wa,
{ia:d,fa:e})};f.getInheritedInstanceCount=function(){return Object.keys(Cc).length};f.getLiveInheritedInstances=function(){var a=[],b;for(b in Cc)Cc.hasOwnProperty(b)&&a.push(Cc[b]);return a};f.flushPendingDeletes=oc;f.setDelayFunction=function(a){mc=a;nc.length&&mc&&mc(oc)};Gc=f.UnboundTypeError=Zb("UnboundTypeError");f.count_emval_handles=function(){for(var a=0,b=5;b<X.length;++b)void 0!==X[b]&&++a;return a};f.get_first_emval=function(){for(var a=5;a<X.length;++a)if(void 0!==X[a])return X[a];return null};
function fb(a,b){var c=Array(ua(a)+1);a=ta(a,c,0,c.length);b&&(c.length=a);return c}
var bd={d:function(a){return mb(a)},c:function(a){"uncaught_exception"in Wa?Wa.Ea++:Wa.Ea=1;throw a;},v:function(){F[ad()>>2]=63;return-1},u:function(a,b){try{if(-1===(a|0)||0===b)var c=-28;else{var d=Rb[a];if(d&&b===d.Kb){var e=pb[d.fd];if(d.Nb&2){var g=d.flags,k=d.offset,l=E.slice(a,a+b);e&&e.ga.Ka&&e.ga.Ka(e,l,k,b,g)}Rb[a]=null;d.fb&&W(d.Lb)}c=0}return c}catch(n){return"undefined"!==typeof Qb&&n instanceof L||z(n),-n.jb}},l:function(a){var b=Sb[a];delete Sb[a];var c=b.Ra,d=b.sa,e=b.Ya,g=e.map(function(k){return k.qb}).concat(e.map(function(k){return k.Ab}));
bc([a],g,function(k){var l={};e.forEach(function(n,m){var q=k[m],w=n.ob,x=n.pb,h=k[m+e.length],p=n.zb,v=n.Bb;l[n.kb]={read:function(t){return q.fromWireType(w(x,t))},write:function(t,D){var A=[];p(v,t,h.toWireType(A,D));Tb(A)}}});return[{name:b.name,fromWireType:function(n){var m={},q;for(q in l)m[q]=l[q].read(n);d(n);return m},toWireType:function(n,m){for(var q in l)if(!(q in m))throw new TypeError('Missing field:  "'+q+'"');var w=c();for(q in l)l[q].write(w,m[q]);null!==n&&n.push(d,w);return w},
argPackAdvance:8,readValueFromPointer:Ub,na:d}]})},z:function(a,b,c,d,e){var g=cc(c);b=R(b);Q(a,{name:b,fromWireType:function(k){return!!k},toWireType:function(k,l){return l?d:e},argPackAdvance:8,readValueFromPointer:function(k){if(1===c)var l=G;else if(2===c)l=ya;else if(4===c)l=F;else throw new TypeError("Unknown boolean type size: "+b);return this.fromWireType(l[k>>g])},na:null})},i:function(a,b,c,d,e,g,k,l,n,m,q,w,x){q=R(q);g=V(e,g);l&&(l=V(k,l));m&&(m=V(n,m));x=V(w,x);var h=Xb(q);rc(h,function(){Jc("Cannot construct "+
q+" due to unbound types",[d])});bc([a,b,c],d?[d]:[],function(p){p=p[0];if(d){var v=p.ea;var t=v.wa}else t=T.prototype;p=Yb(h,function(){if(Object.getPrototypeOf(this)!==D)throw new ec("Use 'new' to construct "+q);if(void 0===A.ua)throw new ec(q+" has no accessible constructor");var Y=A.ua[arguments.length];if(void 0===Y)throw new ec("Tried to invoke ctor of "+q+" with invalid number of parameters ("+arguments.length+") - expected ("+Object.keys(A.ua).toString()+") parameters instead!");return Y.apply(this,
arguments)});var D=Object.create(t,{constructor:{value:p}});p.prototype=D;var A=new sc(q,p,D,x,v,g,l,m);v=new U(q,A,!0,!1);t=new U(q+"*",A,!1,!1);var ha=new U(q+" const*",A,!1,!0);pc[a]={pointerType:t,hb:ha};Fc(h,p);return[v,t,ha]})},h:function(a,b,c,d,e,g){assert(0<b);var k=Kc(b,c);e=V(d,e);var l=[g],n=[];bc([],[a],function(m){m=m[0];var q="constructor "+m.name;void 0===m.ea.ua&&(m.ea.ua=[]);if(void 0!==m.ea.ua[b-1])throw new ec("Cannot register multiple constructors with identical number of parameters ("+
(b-1)+") for class '"+m.name+"'! Overload resolution is currently only performed using the parameter count, not actual type info!");m.ea.ua[b-1]=function(){Jc("Cannot construct "+m.name+" due to unbound types",k)};bc([],k,function(w){m.ea.ua[b-1]=function(){arguments.length!==b-1&&S(q+" called with "+arguments.length+" arguments, expected "+(b-1));n.length=0;l.length=b;for(var x=1;x<b;++x)l[x]=w[x].toWireType(n,arguments[x-1]);x=e.apply(null,l);Tb(n);return w[0].fromWireType(x)};return[]});return[]})},
a:function(a,b,c,d,e,g,k,l){var n=Kc(c,d);b=R(b);g=V(e,g);bc([],[a],function(m){function q(){Jc("Cannot call "+w+" due to unbound types",n)}m=m[0];var w=m.name+"."+b;l&&m.ea.vb.push(b);var x=m.ea.wa,h=x[b];void 0===h||void 0===h.pa&&h.className!==m.name&&h.Fa===c-2?(q.Fa=c-2,q.className=m.name,x[b]=q):(qc(x,b,w),x[b].pa[c-2]=q);bc([],n,function(p){var v=w,t=m,D=g,A=p.length;2>A&&S("argTypes array size mismatch! Must at least get return value and 'this' types!");var ha=null!==p[1]&&null!==t,Y=!1;for(t=
1;t<p.length;++t)if(null!==p[t]&&void 0===p[t].na){Y=!0;break}var uc="void"!==p[0].name,Z="",ia="";for(t=0;t<A-2;++t)Z+=(0!==t?", ":"")+"arg"+t,ia+=(0!==t?", ":"")+"arg"+t+"Wired";v="return function "+Xb(v)+"("+Z+") {\nif (arguments.length !== "+(A-2)+") {\nthrowBindingError('function "+v+" called with ' + arguments.length + ' arguments, expected "+(A-2)+" args!');\n}\n";Y&&(v+="var destructors = [];\n");var vc=Y?"destructors":"null";Z="throwBindingError invoker fn runDestructors retType classParam".split(" ");
D=[S,D,k,Tb,p[0],p[1]];ha&&(v+="var thisWired = classParam.toWireType("+vc+", this);\n");for(t=0;t<A-2;++t)v+="var arg"+t+"Wired = argType"+t+".toWireType("+vc+", arg"+t+"); // "+p[t+2].name+"\n",Z.push("argType"+t),D.push(p[t+2]);ha&&(ia="thisWired"+(0<ia.length?", ":"")+ia);v+=(uc?"var rv = ":"")+"invoker(fn"+(0<ia.length?", ":"")+ia+");\n";if(Y)v+="runDestructors(destructors);\n";else for(t=ha?1:2;t<p.length;++t)A=1===t?"thisWired":"arg"+(t-2)+"Wired",null!==p[t].na&&(v+=A+"_dtor("+A+"); // "+
p[t].name+"\n",Z.push(A+"_dtor"),D.push(p[t].na));uc&&(v+="var ret = retType.fromWireType(rv);\nreturn ret;\n");Z.push(v+"}\n");p=Lc(Z).apply(null,D);void 0===x[b].pa?(p.Fa=c-2,x[b]=p):x[b].pa[c-2]=p;return[]});return[]})},y:function(a,b){b=R(b);Q(a,{name:b,fromWireType:function(c){var d=X[c].value;Nc(c);return d},toWireType:function(c,d){return zc(d)},argPackAdvance:8,readValueFromPointer:Ub,na:null})},n:function(a,b,c){c=cc(c);b=R(b);Q(a,{name:b,fromWireType:function(d){return d},toWireType:function(d,
e){if("number"!==typeof e&&"boolean"!==typeof e)throw new TypeError('Cannot convert "'+xc(e)+'" to '+this.name);return e},argPackAdvance:8,readValueFromPointer:Oc(b,c),na:null})},f:function(a,b,c,d,e){function g(m){return m}b=R(b);-1===e&&(e=4294967295);var k=cc(c);if(0===d){var l=32-8*c;g=function(m){return m<<l>>>l}}var n=-1!=b.indexOf("unsigned");Q(a,{name:b,fromWireType:g,toWireType:function(m,q){if("number"!==typeof q&&"boolean"!==typeof q)throw new TypeError('Cannot convert "'+xc(q)+'" to '+
this.name);if(q<d||q>e)throw new TypeError('Passing a number "'+xc(q)+'" from JS side to C/C++ side to an argument of type "'+b+'", which is outside the valid range ['+d+", "+e+"]!");return n?q>>>0:q|0},argPackAdvance:8,readValueFromPointer:Pc(b,k,0!==d),na:null})},e:function(a,b,c){function d(g){g>>=2;return new e(Ea,H[g+1],H[g])}var e=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array][b];c=R(c);Q(a,{name:c,fromWireType:d,argPackAdvance:8,readValueFromPointer:d},
{rb:!0})},o:function(a,b){b=R(b);var c="std::string"===b;Q(a,{name:b,fromWireType:function(d){var e=H[d>>2];if(c)for(var g=d+4,k=0;k<=e;++k){var l=d+4+k;if(0==E[l]||k==e){g=g?C(E,g,l-g):"";if(void 0===n)var n=g;else n+=String.fromCharCode(0),n+=g;g=l+1}}else{n=Array(e);for(k=0;k<e;++k)n[k]=String.fromCharCode(E[d+4+k]);n=n.join("")}W(d);return n},toWireType:function(d,e){e instanceof ArrayBuffer&&(e=new Uint8Array(e));var g="string"===typeof e;g||e instanceof Uint8Array||e instanceof Uint8ClampedArray||
e instanceof Int8Array||S("Cannot pass non-string to std::string");var k=(c&&g?function(){return ua(e)}:function(){return e.length})(),l=mb(4+k+1);H[l>>2]=k;if(c&&g)ta(e,E,l+4,k+1);else if(g)for(g=0;g<k;++g){var n=e.charCodeAt(g);255<n&&(W(l),S("String has UTF-16 code units that do not fit in 8 bits"));E[l+4+g]=n}else for(g=0;g<k;++g)E[l+4+g]=e[g];null!==d&&d.push(W,l);return l},argPackAdvance:8,readValueFromPointer:Ub,na:function(d){W(d)}})},j:function(a,b,c){c=R(c);if(2===b){var d=wa;var e=za;var g=
Aa;var k=function(){return xa};var l=1}else 4===b&&(d=Ba,e=Ca,g=Da,k=function(){return H},l=2);Q(a,{name:c,fromWireType:function(n){for(var m=H[n>>2],q=k(),w,x=n+4,h=0;h<=m;++h){var p=n+4+h*b;if(0==q[p>>l]||h==m)x=d(x,p-x),void 0===w?w=x:(w+=String.fromCharCode(0),w+=x),x=p+b}W(n);return w},toWireType:function(n,m){"string"!==typeof m&&S("Cannot pass non-string to C++ string type "+c);var q=g(m),w=mb(4+q+b);H[w>>2]=q>>l;e(m,w+4,q+b);null!==n&&n.push(W,w);return w},argPackAdvance:8,readValueFromPointer:Ub,
na:function(n){W(n)}})},q:function(a,b,c,d,e,g){Sb[a]={name:R(b),Ra:V(c,d),sa:V(e,g),Ya:[]}},b:function(a,b,c,d,e,g,k,l,n,m){Sb[a].Ya.push({kb:R(b),qb:c,ob:V(d,e),pb:g,Ab:k,zb:V(l,n),Bb:m})},A:function(a,b){b=R(b);Q(a,{Jb:!0,name:b,argPackAdvance:0,fromWireType:function(){},toWireType:function(){}})},p:Nc,k:function(a){4<a&&(X[a].Ta+=1)},g:function(a,b){var c=P[a];void 0===c&&S("_emval_take_value has unknown type "+Hc(a));a=c.readValueFromPointer(b);return zc(a)},m:function(){z()},r:function(a,b,
c){E.copyWithin(a,b,b+c)},s:function(){z("OOM")},w:function(a,b){var c=0;Rc().forEach(function(d,e){var g=b+c;e=F[a+4*e>>2]=g;for(g=0;g<d.length;++g)G[e++>>0]=d.charCodeAt(g);G[e>>0]=0;c+=d.length+1});return 0},x:function(a,b){var c=Rc();F[a>>2]=c.length;var d=0;c.forEach(function(e){d+=e.length+1});F[b>>2]=d;return 0},memory:pa,t:function(a,b,c,d){return Yc(a,b,c,d)},table:qa};
(function(){function a(e){f.asm=e.exports;J--;f.monitorRunDependencies&&f.monitorRunDependencies(J);0==J&&(null!==Oa&&(clearInterval(Oa),Oa=null),Pa&&(e=Pa,Pa=null,e()))}function b(e){a(e.instance)}function c(e){return Ua().then(function(g){return WebAssembly.instantiate(g,d)}).then(e,function(g){B("failed to asynchronously prepare wasm: "+g);z(g)})}var d={a:bd};J++;f.monitorRunDependencies&&f.monitorRunDependencies(J);if(f.instantiateWasm)try{return f.instantiateWasm(d,a)}catch(e){return B("Module.instantiateWasm callback failed with error: "+
e),!1}(function(){if(oa||"function"!==typeof WebAssembly.instantiateStreaming||Ra()||Qa("file://")||"function"!==typeof fetch)return c(b);fetch(K,{credentials:"same-origin"}).then(function(e){return WebAssembly.instantiateStreaming(e,d).then(b,function(g){B("wasm streaming compile failed: "+g);B("falling back to ArrayBuffer instantiation");return c(b)})})})();return{}})();
var Va=f.___wasm_call_ctors=function(){return(Va=f.___wasm_call_ctors=f.asm.B).apply(null,arguments)},mb=f._malloc=function(){return(mb=f._malloc=f.asm.C).apply(null,arguments)},Ic=f.___getTypeName=function(){return(Ic=f.___getTypeName=f.asm.D).apply(null,arguments)};f.___embind_register_native_and_builtin_types=function(){return(f.___embind_register_native_and_builtin_types=f.asm.E).apply(null,arguments)};
var ad=f.___errno_location=function(){return(ad=f.___errno_location=f.asm.F).apply(null,arguments)},W=f._free=function(){return(W=f._free=f.asm.G).apply(null,arguments)};f.dynCall_i=function(){return(f.dynCall_i=f.asm.H).apply(null,arguments)};f.dynCall_vi=function(){return(f.dynCall_vi=f.asm.I).apply(null,arguments)};f.dynCall_iii=function(){return(f.dynCall_iii=f.asm.J).apply(null,arguments)};f.dynCall_viii=function(){return(f.dynCall_viii=f.asm.K).apply(null,arguments)};
f.dynCall_ii=function(){return(f.dynCall_ii=f.asm.L).apply(null,arguments)};f.dynCall_iiii=function(){return(f.dynCall_iiii=f.asm.M).apply(null,arguments)};f.dynCall_iiiii=function(){return(f.dynCall_iiiii=f.asm.N).apply(null,arguments)};f.dynCall_vii=function(){return(f.dynCall_vii=f.asm.O).apply(null,arguments)};f.dynCall_viiii=function(){return(f.dynCall_viiii=f.asm.P).apply(null,arguments)};f.dynCall_viiiii=function(){return(f.dynCall_viiiii=f.asm.Q).apply(null,arguments)};
f.dynCall_iiiiii=function(){return(f.dynCall_iiiiii=f.asm.R).apply(null,arguments)};f.dynCall_viiiiii=function(){return(f.dynCall_viiiiii=f.asm.S).apply(null,arguments)};f.dynCall_iiiiiii=function(){return(f.dynCall_iiiiiii=f.asm.T).apply(null,arguments)};f.dynCall_iidiiii=function(){return(f.dynCall_iidiiii=f.asm.U).apply(null,arguments)};f.dynCall_iiiiiiiii=function(){return(f.dynCall_iiiiiiiii=f.asm.V).apply(null,arguments)};
f.dynCall_iiiiij=function(){return(f.dynCall_iiiiij=f.asm.W).apply(null,arguments)};f.dynCall_iiiiid=function(){return(f.dynCall_iiiiid=f.asm.X).apply(null,arguments)};f.dynCall_iiiiijj=function(){return(f.dynCall_iiiiijj=f.asm.Y).apply(null,arguments)};f.dynCall_iiiiiiii=function(){return(f.dynCall_iiiiiiii=f.asm.Z).apply(null,arguments)};f.dynCall_iiiiiijj=function(){return(f.dynCall_iiiiiijj=f.asm._).apply(null,arguments)};f.dynCall_v=function(){return(f.dynCall_v=f.asm.$).apply(null,arguments)};
var cd;Pa=function dd(){cd||ed();cd||(Pa=dd)};
function ed(){function a(){if(!cd&&(cd=!0,f.calledRun=!0,!ra)){f.noFSInit||Mb||(Mb=!0,Lb(),f.stdin=f.stdin,f.stdout=f.stdout,f.stderr=f.stderr,f.stdin?Ob("stdin",f.stdin):Ib("/dev/tty","/dev/stdin"),f.stdout?Ob("stdout",null,f.stdout):Ib("/dev/tty","/dev/stdout"),f.stderr?Ob("stderr",null,f.stderr):Ib("/dev/tty1","/dev/stderr"),Jb("/dev/stdin","r"),Jb("/dev/stdout","w"),Jb("/dev/stderr","w"));Ia(Ka);sb=!1;Ia(La);aa(f);if(f.onRuntimeInitialized)f.onRuntimeInitialized();if(f.postRun)for("function"==
typeof f.postRun&&(f.postRun=[f.postRun]);f.postRun.length;){var b=f.postRun.shift();Ma.unshift(b)}Ia(Ma)}}if(!(0<J)){if(f.preRun)for("function"==typeof f.preRun&&(f.preRun=[f.preRun]);f.preRun.length;)Na();Ia(Ja);0<J||(f.setStatus?(f.setStatus("Running..."),setTimeout(function(){setTimeout(function(){f.setStatus("")},1);a()},1)):a())}}f.run=ed;if(f.preInit)for("function"==typeof f.preInit&&(f.preInit=[f.preInit]);0<f.preInit.length;)f.preInit.pop()();noExitRuntime=!0;ed();


  return Module.ready
}
);
})();
if (typeof exports === 'object' && typeof module === 'object')
      module.exports = Module;
    else if (typeof define === 'function' && define['amd'])
      define([], function() { return Module; });
    else if (typeof exports === 'object')
      exports["Module"] = Module;
    