
var Module = (function() {
  var _scriptDir = typeof document !== 'undefined' && document.currentScript ? document.currentScript.src : undefined;
  if (typeof __filename !== 'undefined') _scriptDir = _scriptDir || __filename;
  return (
function(Module) {
  Module = Module || {};


var f;f||(f=typeof Module !== 'undefined' ? Module : {});var aa;f.ready=new Promise(function(a){aa=a});var ba={},p;for(p in f)f.hasOwnProperty(p)&&(ba[p]=f[p]);var ca="./this.program",da=!1,v=!1,ea=!1,fa=!1;da="object"===typeof window;v="function"===typeof importScripts;ea="object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node;fa=!da&&!ea&&!v;var y="",ha,ia,la,ma;
if(ea)y=v?require("path").dirname(y)+"/":__dirname+"/",ha=function(a,b){la||(la=require("fs"));ma||(ma=require("path"));a=ma.normalize(a);return la.readFileSync(a,b?null:"utf8")},ia=function(a){a=ha(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a},1<process.argv.length&&(ca=process.argv[1].replace(/\\/g,"/")),process.argv.slice(2),process.on("uncaughtException",function(a){throw a;}),process.on("unhandledRejection",z),f.inspect=function(){return"[Emscripten Module object]"};else if(fa)"undefined"!=
typeof read&&(ha=function(a){return read(a)}),ia=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");assert("object"===typeof a);return a},"undefined"!==typeof print&&("undefined"===typeof console&&(console={}),console.log=print,console.warn=console.error="undefined"!==typeof printErr?printErr:print);else if(da||v)v?y=self.location.href:document.currentScript&&(y=document.currentScript.src),_scriptDir&&(y=_scriptDir),0!==y.indexOf("blob:")?y=y.substr(0,
y.lastIndexOf("/")+1):y="",ha=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},v&&(ia=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});var na=f.print||console.log.bind(console),B=f.printErr||console.warn.bind(console);for(p in ba)ba.hasOwnProperty(p)&&(f[p]=ba[p]);ba=null;f.thisProgram&&(ca=f.thisProgram);var oa;f.wasmBinary&&(oa=f.wasmBinary);var noExitRuntime;
f.noExitRuntime&&(noExitRuntime=f.noExitRuntime);"object"!==typeof WebAssembly&&B("no native wasm support detected");var pa,qa=new WebAssembly.Table({initial:565,maximum:565,element:"anyfunc"}),ra=!1;function assert(a,b){a||z("Assertion failed: "+b)}var sa="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function C(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.subarray&&sa)return sa.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var g=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|g);else{var k=a[b++]&63;e=224==(e&240)?(e&15)<<12|g<<6|k:(e&7)<<18|g<<12|k<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d}
function ta(a,b,c,d){if(!(0<d))return 0;var e=c;d=c+d-1;for(var g=0;g<a.length;++g){var k=a.charCodeAt(g);if(55296<=k&&57343>=k){var l=a.charCodeAt(++g);k=65536+((k&1023)<<10)|l&1023}if(127>=k){if(c>=d)break;b[c++]=k}else{if(2047>=k){if(c+1>=d)break;b[c++]=192|k>>6}else{if(65535>=k){if(c+2>=d)break;b[c++]=224|k>>12}else{if(c+3>=d)break;b[c++]=240|k>>18;b[c++]=128|k>>12&63}b[c++]=128|k>>6&63}b[c++]=128|k&63}}b[c]=0;return c-e}
function ua(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}var va="undefined"!==typeof TextDecoder?new TextDecoder("utf-16le"):void 0;function wa(a,b){var c=a>>1;for(var d=c+b/2;!(c>=d)&&xa[c];)++c;c<<=1;if(32<c-a&&va)return va.decode(E.subarray(a,c));c=0;for(d="";;){var e=ya[a+2*c>>1];if(0==e||c==b/2)return d;++c;d+=String.fromCharCode(e)}}
function za(a,b,c){void 0===c&&(c=2147483647);if(2>c)return 0;c-=2;var d=b;c=c<2*a.length?c/2:a.length;for(var e=0;e<c;++e)ya[b>>1]=a.charCodeAt(e),b+=2;ya[b>>1]=0;return b-d}function Aa(a){return 2*a.length}function Ba(a,b){for(var c=0,d="";!(c>=b/4);){var e=F[a+4*c>>2];if(0==e)break;++c;65536<=e?(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023)):d+=String.fromCharCode(e)}return d}
function Ca(a,b,c){void 0===c&&(c=2147483647);if(4>c)return 0;var d=b;c=d+c-4;for(var e=0;e<a.length;++e){var g=a.charCodeAt(e);if(55296<=g&&57343>=g){var k=a.charCodeAt(++e);g=65536+((g&1023)<<10)|k&1023}F[b>>2]=g;b+=4;if(b+4>c)break}F[b>>2]=0;return b-d}function Da(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&++c;b+=4}return b}var Ea,G,E,ya,xa,F,H,Fa,Ga,Ha=f.INITIAL_MEMORY||16777216;
f.wasmMemory?pa=f.wasmMemory:pa=new WebAssembly.Memory({initial:Ha/65536,maximum:Ha/65536});pa&&(Ea=pa.buffer);Ha=Ea.byteLength;var I=Ea;Ea=I;f.HEAP8=G=new Int8Array(I);f.HEAP16=ya=new Int16Array(I);f.HEAP32=F=new Int32Array(I);f.HEAPU8=E=new Uint8Array(I);f.HEAPU16=xa=new Uint16Array(I);f.HEAPU32=H=new Uint32Array(I);f.HEAPF32=Fa=new Float32Array(I);f.HEAPF64=Ga=new Float64Array(I);F[8252]=5276048;
function Ia(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(f);else{var c=b.sb;"number"===typeof c?void 0===b.Va?f.dynCall_v(c):f.dynCall_vi(c,b.Va):c(void 0===b.Va?null:b.Va)}}}var Ja=[],Ka=[],La=[],Ma=[];function Na(){var a=f.preRun.shift();Ja.unshift(a)}var Oa=Math.abs,Pa=Math.ceil,Qa=Math.floor,Ra=Math.min,J=0,Sa=null,Ta=null;f.preloadedImages={};f.preloadedAudios={};
function z(a){if(f.onAbort)f.onAbort(a);na(a);B(a);ra=!0;throw new WebAssembly.RuntimeError("abort("+a+"). Build with -s ASSERTIONS=1 for more info.");}function Ua(a){var b=K;return String.prototype.startsWith?b.startsWith(a):0===b.indexOf(a)}function Va(){return Ua("data:application/octet-stream;base64,")}var K="chess-wasm.wasm";if(!Va()){var Wa=K;K=f.locateFile?f.locateFile(Wa,y):y+Wa}
function Xa(){try{if(oa)return new Uint8Array(oa);if(ia)return ia(K);throw"both async and sync fetching of the wasm failed";}catch(a){z(a)}}function Ya(){return oa||!da&&!v||"function"!==typeof fetch||Ua("file://")?new Promise(function(a){a(Xa())}):fetch(K,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+K+"'";return a.arrayBuffer()}).catch(function(){return Xa()})}var Za,$a;Ka.push({sb:function(){ab()}});function bb(){return 0<bb.Ma}
function cb(a,b){for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a}function db(a){var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=cb(a.split("/").filter(function(d){return!!d}),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a}
function eb(a){var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b}function fb(a){if("/"===a)return"/";var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)}
function gb(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!==typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=cb(a.split("/").filter(function(d){return!!d}),!b).join("/");return(b?"/":"")+a||"."}var hb=[];function ib(a,b){hb[a]={input:[],output:[],Fa:b};jb(a,kb)}
var kb={open:function(a){var b=hb[a.node.rdev];if(!b)throw new L(43);a.tty=b;a.seekable=!1},close:function(a){a.tty.Fa.flush(a.tty)},flush:function(a){a.tty.Fa.flush(a.tty)},read:function(a,b,c,d){if(!a.tty||!a.tty.Fa.jb)throw new L(60);for(var e=0,g=0;g<d;g++){try{var k=a.tty.Fa.jb(a.tty)}catch(l){throw new L(29);}if(void 0===k&&0===e)throw new L(6);if(null===k||void 0===k)break;e++;b[c+g]=k}e&&(a.node.timestamp=Date.now());return e},write:function(a,b,c,d){if(!a.tty||!a.tty.Fa.Ya)throw new L(60);
try{for(var e=0;e<d;e++)a.tty.Fa.Ya(a.tty,b[c+e])}catch(g){throw new L(29);}d&&(a.node.timestamp=Date.now());return e}},mb={jb:function(a){if(!a.input.length){var b=null;if(ea){var c=Buffer.Ma?Buffer.Ma(256):new Buffer(256),d=0;try{d=la.readSync(process.stdin.fd,c,0,256,null)}catch(e){if(-1!=e.toString().indexOf("EOF"))d=0;else throw e;}0<d?b=c.slice(0,d).toString("utf-8"):b=null}else"undefined"!=typeof window&&"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==
typeof readline&&(b=readline(),null!==b&&(b+="\n"));if(!b)return null;a.input=lb(b,!0)}return a.input.shift()},Ya:function(a,b){null===b||10===b?(na(C(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(na(C(a.output,0)),a.output=[])}},nb={Ya:function(a,b){null===b||10===b?(B(C(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(B(C(a.output,0)),a.output=[])}},M={ua:null,ya:function(){return M.createNode(null,
"/",16895,0)},createNode:function(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new L(63);M.ua||(M.ua={dir:{node:{Aa:M.ja.Aa,wa:M.ja.wa,lookup:M.ja.lookup,Pa:M.ja.Pa,rename:M.ja.rename,unlink:M.ja.unlink,rmdir:M.ja.rmdir,readdir:M.ja.readdir,symlink:M.ja.symlink},stream:{Ca:M.ka.Ca}},file:{node:{Aa:M.ja.Aa,wa:M.ja.wa},stream:{Ca:M.ka.Ca,read:M.ka.read,write:M.ka.write,bb:M.ka.bb,kb:M.ka.kb,Ra:M.ka.Ra}},link:{node:{Aa:M.ja.Aa,wa:M.ja.wa,readlink:M.ja.readlink},stream:{}},cb:{node:{Aa:M.ja.Aa,
wa:M.ja.wa},stream:ob}});c=pb(a,b,c,d);16384===(c.mode&61440)?(c.ja=M.ua.dir.node,c.ka=M.ua.dir.stream,c.ia={}):32768===(c.mode&61440)?(c.ja=M.ua.file.node,c.ka=M.ua.file.stream,c.na=0,c.ia=null):40960===(c.mode&61440)?(c.ja=M.ua.link.node,c.ka=M.ua.link.stream):8192===(c.mode&61440)&&(c.ja=M.ua.cb.node,c.ka=M.ua.cb.stream);c.timestamp=Date.now();a&&(a.ia[b]=c);return c},Pb:function(a){if(a.ia&&a.ia.subarray){for(var b=[],c=0;c<a.na;++c)b.push(a.ia[c]);return b}return a.ia},Qb:function(a){return a.ia?
a.ia.subarray?a.ia.subarray(0,a.na):new Uint8Array(a.ia):new Uint8Array(0)},fb:function(a,b){var c=a.ia?a.ia.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),c=a.ia,a.ia=new Uint8Array(b),0<a.na&&a.ia.set(c.subarray(0,a.na),0))},Eb:function(a,b){if(a.na!=b)if(0==b)a.ia=null,a.na=0;else{if(!a.ia||a.ia.subarray){var c=a.ia;a.ia=new Uint8Array(b);c&&a.ia.set(c.subarray(0,Math.min(b,a.na)))}else if(a.ia||(a.ia=[]),a.ia.length>b)a.ia.length=b;else for(;a.ia.length<b;)a.ia.push(0);
a.na=b}},ja:{Aa:function(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;16384===(a.mode&61440)?b.size=4096:32768===(a.mode&61440)?b.size=a.na:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.atime=new Date(a.timestamp);b.mtime=new Date(a.timestamp);b.ctime=new Date(a.timestamp);b.ob=4096;b.blocks=Math.ceil(b.size/b.ob);return b},wa:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==
b.size&&M.Eb(a,b.size)},lookup:function(){throw qb[44];},Pa:function(a,b,c,d){return M.createNode(a,b,c,d)},rename:function(a,b,c){if(16384===(a.mode&61440)){try{var d=rb(b,c)}catch(g){}if(d)for(var e in d.ia)throw new L(55);}delete a.parent.ia[a.name];a.name=c;b.ia[c]=a;a.parent=b},unlink:function(a,b){delete a.ia[b]},rmdir:function(a,b){var c=rb(a,b),d;for(d in c.ia)throw new L(55);delete a.ia[b]},readdir:function(a){var b=[".",".."],c;for(c in a.ia)a.ia.hasOwnProperty(c)&&b.push(c);return b},symlink:function(a,
b,c){a=M.createNode(a,b,41471,0);a.link=c;return a},readlink:function(a){if(40960!==(a.mode&61440))throw new L(28);return a.link}},ka:{read:function(a,b,c,d,e){var g=a.node.ia;if(e>=a.node.na)return 0;a=Math.min(a.node.na-e,d);if(8<a&&g.subarray)b.set(g.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=g[e+d];return a},write:function(a,b,c,d,e,g){if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.ia||a.ia.subarray)){if(g)return a.ia=b.subarray(c,c+d),a.na=d;if(0===a.na&&0===e)return a.ia=
b.slice(c,c+d),a.na=d;if(e+d<=a.na)return a.ia.set(b.subarray(c,c+d),e),d}M.fb(a,e+d);if(a.ia.subarray&&b.subarray)a.ia.set(b.subarray(c,c+d),e);else for(g=0;g<d;g++)a.ia[e+g]=b[c+g];a.na=Math.max(a.na,e+d);return d},Ca:function(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.na);if(0>b)throw new L(28);return b},bb:function(a,b,c){M.fb(a.node,b+c);a.node.na=Math.max(a.node.na,b+c)},kb:function(a,b,c,d,e,g){assert(0===b);if(32768!==(a.node.mode&61440))throw new L(43);a=a.node.ia;
if(g&2||a.buffer!==Ea){if(0<d||d+c<a.length)a.subarray?a=a.subarray(d,d+c):a=Array.prototype.slice.call(a,d,d+c);d=!0;c=sb(c);if(!c)throw new L(48);G.set(a,c)}else d=!1,c=a.byteOffset;return{ma:c,nb:d}},Ra:function(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new L(43);if(e&2)return 0;M.ka.write(a,b,0,d,c,!1);return 0}}},tb=null,ub={},vb=[],wb=1,xb=null,yb=!0,zb={},L=null,qb={};
function N(a,b){a=gb("/",a);b=b||{};if(!a)return{path:"",node:null};var c={ib:!0,$a:0},d;for(d in c)void 0===b[d]&&(b[d]=c[d]);if(8<b.$a)throw new L(32);a=cb(a.split("/").filter(function(k){return!!k}),!1);var e=tb;c="/";for(d=0;d<a.length;d++){var g=d===a.length-1;if(g&&b.parent)break;e=rb(e,a[d]);c=db(c+"/"+a[d]);e.Qa&&(!g||g&&b.ib)&&(e=e.Qa.root);if(!g||b.hb)for(g=0;40960===(e.mode&61440);)if(e=Ab(c),c=gb(eb(c),e),e=N(c,{$a:b.$a}).node,40<g++)throw new L(32);}return{path:c,node:e}}
function Bb(a){for(var b;;){if(a===a.parent)return a=a.ya.lb,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}}function Cb(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%xb.length}function rb(a,b){var c;if(c=(c=Db(a,"x"))?c:a.ja.lookup?0:2)throw new L(c,a);for(c=xb[Cb(a.id,b)];c;c=c.Ab){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.ja.lookup(a,b)}
function pb(a,b,c,d){a=new Eb(a,b,c,d);b=Cb(a.parent.id,a.name);a.Ab=xb[b];return xb[b]=a}var Fb={r:0,rs:1052672,"r+":2,w:577,wx:705,xw:705,"w+":578,"wx+":706,"xw+":706,a:1089,ax:1217,xa:1217,"a+":1090,"ax+":1218,"xa+":1218};function Gb(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}function Db(a,b){if(yb)return 0;if(-1===b.indexOf("r")||a.mode&292){if(-1!==b.indexOf("w")&&!(a.mode&146)||-1!==b.indexOf("x")&&!(a.mode&73))return 2}else return 2;return 0}
function Hb(a,b){try{return rb(a,b),20}catch(c){}return Db(a,"wx")}function Ib(){var a=4096;for(var b=0;b<=a;b++)if(!vb[b])return b;throw new L(33);}function Jb(a){Kb||(Kb=function(){},Kb.prototype={});var b=new Kb,c;for(c in a)b[c]=a[c];a=b;b=Ib();a.fd=b;return vb[b]=a}var ob={open:function(a){a.ka=ub[a.node.rdev].ka;a.ka.open&&a.ka.open(a)},Ca:function(){throw new L(70);}};function jb(a,b){ub[a]={ka:b}}
function Lb(a,b){var c="/"===b,d=!b;if(c&&tb)throw new L(10);if(!c&&!d){var e=N(b,{ib:!1});b=e.path;e=e.node;if(e.Qa)throw new L(10);if(16384!==(e.mode&61440))throw new L(54);}b={type:a,Ub:{},lb:b,zb:[]};a=a.ya(b);a.ya=b;b.root=a;c?tb=a:e&&(e.Qa=b,e.ya&&e.ya.zb.push(b))}function Mb(a,b,c){var d=N(a,{parent:!0}).node;a=fb(a);if(!a||"."===a||".."===a)throw new L(28);var e=Hb(d,a);if(e)throw new L(e);if(!d.ja.Pa)throw new L(63);return d.ja.Pa(d,a,b,c)}function O(a){Mb(a,16895,0)}
function Nb(a,b,c){"undefined"===typeof c&&(c=b,b=438);Mb(a,b|8192,c)}function Ob(a,b){if(!gb(a))throw new L(44);var c=N(b,{parent:!0}).node;if(!c)throw new L(44);b=fb(b);var d=Hb(c,b);if(d)throw new L(d);if(!c.ja.symlink)throw new L(63);c.ja.symlink(c,b,a)}function Ab(a){a=N(a).node;if(!a)throw new L(44);if(!a.ja.readlink)throw new L(28);return gb(Bb(a.parent),a.ja.readlink(a))}
function Pb(a,b){if(""===a)throw new L(44);if("string"===typeof b){var c=Fb[b];if("undefined"===typeof c)throw Error("Unknown file open mode: "+b);b=c}var d=b&64?("undefined"===typeof d?438:d)&4095|32768:0;if("object"===typeof a)var e=a;else{a=db(a);try{e=N(a,{hb:!(b&131072)}).node}catch(k){}}c=!1;if(b&64)if(e){if(b&128)throw new L(20);}else e=Mb(a,d,0),c=!0;if(!e)throw new L(44);8192===(e.mode&61440)&&(b&=-513);if(b&65536&&16384!==(e.mode&61440))throw new L(54);if(!c&&(d=e?40960===(e.mode&61440)?
32:16384===(e.mode&61440)&&("r"!==Gb(b)||b&512)?31:Db(e,Gb(b)):44))throw new L(d);if(b&512){d=e;var g;"string"===typeof d?g=N(d,{hb:!0}).node:g=d;if(!g.ja.wa)throw new L(63);if(16384===(g.mode&61440))throw new L(31);if(32768!==(g.mode&61440))throw new L(28);if(d=Db(g,"w"))throw new L(d);g.ja.wa(g,{size:0,timestamp:Date.now()})}b&=-131713;e=Jb({node:e,path:Bb(e),flags:b,seekable:!0,position:0,ka:e.ka,Ob:[],error:!1});e.ka.open&&e.ka.open(e);!f.logReadFiles||b&1||(Qb||(Qb={}),a in Qb||(Qb[a]=1,B("FS.trackingDelegate error on read file: "+
a)));try{zb.onOpenFile&&(e=0,1!==(b&2097155)&&(e|=1),0!==(b&2097155)&&(e|=2),zb.onOpenFile(a,e))}catch(k){B("FS.trackingDelegate['onOpenFile']('"+a+"', flags) threw an exception: "+k.message)}}function Rb(a,b,c){if(null===a.fd)throw new L(8);if(!a.seekable||!a.ka.Ca)throw new L(70);if(0!=c&&1!=c&&2!=c)throw new L(28);a.position=a.ka.Ca(a,b,c);a.Ob=[]}
function Sb(){L||(L=function(a,b){this.node=b;this.Fb=function(c){this.Ha=c};this.Fb(a);this.message="FS error"},L.prototype=Error(),L.prototype.constructor=L,[44].forEach(function(a){qb[a]=new L(a);qb[a].stack="<generic error, no stack>"}))}var Tb;function Ub(a,b){var c=0;a&&(c|=365);b&&(c|=146);return c}
function Vb(a,b,c){a=db("/dev/"+a);var d=Ub(!!b,!!c);Wb||(Wb=64);var e=Wb++<<8|0;jb(e,{open:function(g){g.seekable=!1},close:function(){c&&c.buffer&&c.buffer.length&&c(10)},read:function(g,k,l,q){for(var m=0,r=0;r<q;r++){try{var w=b()}catch(x){throw new L(29);}if(void 0===w&&0===m)throw new L(6);if(null===w||void 0===w)break;m++;k[l+r]=w}m&&(g.node.timestamp=Date.now());return m},write:function(g,k,l,q){for(var m=0;m<q;m++)try{c(k[l+m])}catch(r){throw new L(29);}q&&(g.node.timestamp=Date.now());return m}});
Nb(a,d,e)}var Wb,Xb={},Kb,Qb,Yb={};function Zb(a){a=vb[a];if(!a)throw new L(8);return a}var $b={};function ac(a){for(;a.length;){var b=a.pop();a.pop()(b)}}function bc(a){return this.fromWireType(H[a>>2])}var cc={},P={},dc={};function ec(a){if(void 0===a)return"_unknown";a=a.replace(/[^a-zA-Z0-9_]/g,"$");var b=a.charCodeAt(0);return 48<=b&&57>=b?"_"+a:a}
function fc(a,b){a=ec(a);return(new Function("body","return function "+a+'() {\n    "use strict";    return body.apply(this, arguments);\n};\n'))(b)}function hc(a){var b=Error,c=fc(a,function(d){this.name=a;this.message=d;d=Error(d).stack;void 0!==d&&(this.stack=this.toString()+"\n"+d.replace(/^Error(:[^\n]*)?\n/,""))});c.prototype=Object.create(b.prototype);c.prototype.constructor=c;c.prototype.toString=function(){return void 0===this.message?this.name:this.name+": "+this.message};return c}
var ic=void 0;function jc(a){throw new ic(a);}function kc(a,b,c){function d(l){l=c(l);l.length!==a.length&&jc("Mismatched type converter count");for(var q=0;q<a.length;++q)Q(a[q],l[q])}a.forEach(function(l){dc[l]=b});var e=Array(b.length),g=[],k=0;b.forEach(function(l,q){P.hasOwnProperty(l)?e[q]=P[l]:(g.push(l),cc.hasOwnProperty(l)||(cc[l]=[]),cc[l].push(function(){e[q]=P[l];++k;k===g.length&&d(e)}))});0===g.length&&d(e)}
function lc(a){switch(a){case 1:return 0;case 2:return 1;case 4:return 2;case 8:return 3;default:throw new TypeError("Unknown type size: "+a);}}var mc=void 0;function R(a){for(var b="";E[a];)b+=mc[E[a++]];return b}var nc=void 0;function S(a){throw new nc(a);}
function Q(a,b,c){c=c||{};if(!("argPackAdvance"in b))throw new TypeError("registerType registeredInstance requires argPackAdvance");var d=b.name;a||S('type "'+d+'" must have a positive integer typeid pointer');if(P.hasOwnProperty(a)){if(c.yb)return;S("Cannot register type '"+d+"' twice")}P[a]=b;delete dc[a];cc.hasOwnProperty(a)&&(b=cc[a],delete cc[a],b.forEach(function(e){e()}))}function oc(a){return{count:a.count,Da:a.Da,Ia:a.Ia,ma:a.ma,oa:a.oa,qa:a.qa,ra:a.ra}}
function pc(a){S(a.ha.oa.la.name+" instance already deleted")}var qc=!1;function rc(){}function sc(a){--a.count.value;0===a.count.value&&(a.qa?a.ra.za(a.qa):a.oa.la.za(a.ma))}
function tc(a){if("undefined"===typeof FinalizationGroup)return tc=function(b){return b},a;qc=new FinalizationGroup(function(b){for(var c=b.next();!c.done;c=b.next())c=c.value,c.ma?sc(c):console.warn("object already deleted: "+c.ma)});tc=function(b){qc.register(b,b.ha,b.ha);return b};rc=function(b){qc.unregister(b.ha)};return tc(a)}var uc=void 0,vc=[];function wc(){for(;vc.length;){var a=vc.pop();a.ha.Da=!1;a["delete"]()}}function T(){}var xc={};
function yc(a,b,c){if(void 0===a[b].va){var d=a[b];a[b]=function(){a[b].va.hasOwnProperty(arguments.length)||S("Function '"+c+"' called with an invalid number of arguments ("+arguments.length+") - expects one of ("+a[b].va+")!");return a[b].va[arguments.length].apply(this,arguments)};a[b].va=[];a[b].va[d.La]=d}}
function Bc(a,b){f.hasOwnProperty(a)?(S("Cannot register public name '"+a+"' twice"),yc(f,a,a),f.hasOwnProperty(void 0)&&S("Cannot register multiple overloads of a function with the same number of arguments (undefined)!"),f[a].va[void 0]=b):f[a]=b}function Cc(a,b,c,d,e,g,k,l){this.name=a;this.constructor=b;this.Ea=c;this.za=d;this.sa=e;this.tb=g;this.Ka=k;this.qb=l;this.Cb=[]}
function Dc(a,b,c){for(;b!==c;)b.Ka||S("Expected null or instance of "+c.name+", got an instance of "+b.name),a=b.Ka(a),b=b.sa;return a}function Ec(a,b){if(null===b)return this.Xa&&S("null is not a valid "+this.name),0;b.ha||S('Cannot pass "'+Fc(b)+'" as a '+this.name);b.ha.ma||S("Cannot pass deleted object as a pointer of type "+this.name);return Dc(b.ha.ma,b.ha.oa.la,this.la)}
function Gc(a,b){if(null===b){this.Xa&&S("null is not a valid "+this.name);if(this.Oa){var c=this.Za();null!==a&&a.push(this.za,c);return c}return 0}b.ha||S('Cannot pass "'+Fc(b)+'" as a '+this.name);b.ha.ma||S("Cannot pass deleted object as a pointer of type "+this.name);!this.Na&&b.ha.oa.Na&&S("Cannot convert argument of type "+(b.ha.ra?b.ha.ra.name:b.ha.oa.name)+" to parameter type "+this.name);c=Dc(b.ha.ma,b.ha.oa.la,this.la);if(this.Oa)switch(void 0===b.ha.qa&&S("Passing raw pointer to smart pointer is illegal"),
this.Jb){case 0:b.ha.ra===this?c=b.ha.qa:S("Cannot convert argument of type "+(b.ha.ra?b.ha.ra.name:b.ha.oa.name)+" to parameter type "+this.name);break;case 1:c=b.ha.qa;break;case 2:if(b.ha.ra===this)c=b.ha.qa;else{var d=b.clone();c=this.Db(c,Hc(function(){d["delete"]()}));null!==a&&a.push(this.za,c)}break;default:S("Unsupporting sharing policy")}return c}
function Ic(a,b){if(null===b)return this.Xa&&S("null is not a valid "+this.name),0;b.ha||S('Cannot pass "'+Fc(b)+'" as a '+this.name);b.ha.ma||S("Cannot pass deleted object as a pointer of type "+this.name);b.ha.oa.Na&&S("Cannot convert argument of type "+b.ha.oa.name+" to parameter type "+this.name);return Dc(b.ha.ma,b.ha.oa.la,this.la)}function Jc(a,b,c){if(b===c)return a;if(void 0===c.sa)return null;a=Jc(a,b,c.sa);return null===a?null:c.qb(a)}var Kc={};
function Lc(a,b){for(void 0===b&&S("ptr should not be undefined");a.sa;)b=a.Ka(b),a=a.sa;return Kc[b]}function Mc(a,b){b.oa&&b.ma||jc("makeClassHandle requires ptr and ptrType");!!b.ra!==!!b.qa&&jc("Both smartPtrType and smartPtr must be specified");b.count={value:1};return tc(Object.create(a,{ha:{value:b}}))}
function U(a,b,c,d){this.name=a;this.la=b;this.Xa=c;this.Na=d;this.Oa=!1;this.za=this.Db=this.Za=this.mb=this.Jb=this.Bb=void 0;void 0!==b.sa?this.toWireType=Gc:(this.toWireType=d?Ec:Ic,this.ta=null)}function Nc(a,b){f.hasOwnProperty(a)||jc("Replacing nonexistant public symbol");f[a]=b;f[a].La=void 0}
function V(a,b){a=R(a);var c=f["dynCall_"+a];for(var d=[],e=1;e<a.length;++e)d.push("a"+e);e="return function dynCall_"+(a+"_"+b)+"("+d.join(", ")+") {\n";e+="    return dynCall(rawFunction"+(d.length?", ":"")+d.join(", ")+");\n";c=(new Function("dynCall","rawFunction",e+"};\n"))(c,b);"function"!==typeof c&&S("unknown function pointer with signature "+a+": "+b);return c}var Oc=void 0;function Pc(a){a=Qc(a);var b=R(a);W(a);return b}
function Rc(a,b){function c(g){e[g]||P[g]||(dc[g]?dc[g].forEach(c):(d.push(g),e[g]=!0))}var d=[],e={};b.forEach(c);throw new Oc(a+": "+d.map(Pc).join([", "]));}function Sc(a,b){for(var c=[],d=0;d<a;d++)c.push(F[(b>>2)+d]);return c}
function Tc(a){var b=Function;if(!(b instanceof Function))throw new TypeError("new_ called with constructor type "+typeof b+" which is not a function");var c=fc(b.name||"unknownFunctionName",function(){});c.prototype=b.prototype;c=new c;a=b.apply(c,a);return a instanceof Object?a:c}var Uc=[],X=[{},{value:void 0},{value:null},{value:!0},{value:!1}];function Vc(a){4<a&&0===--X[a].ab&&(X[a]=void 0,Uc.push(a))}
function Hc(a){switch(a){case void 0:return 1;case null:return 2;case !0:return 3;case !1:return 4;default:var b=Uc.length?Uc.pop():X.length;X[b]={ab:1,value:a};return b}}function Fc(a){if(null===a)return"null";var b=typeof a;return"object"===b||"array"===b||"function"===b?a.toString():""+a}function Wc(a,b){switch(b){case 2:return function(c){return this.fromWireType(Fa[c>>2])};case 3:return function(c){return this.fromWireType(Ga[c>>3])};default:throw new TypeError("Unknown float type: "+a);}}
function Xc(a,b,c){switch(b){case 0:return c?function(d){return G[d]}:function(d){return E[d]};case 1:return c?function(d){return ya[d>>1]}:function(d){return xa[d>>1]};case 2:return c?function(d){return F[d>>2]}:function(d){return H[d>>2]};default:throw new TypeError("Unknown integer type: "+a);}}var Yc={};
function Zc(){if(!$c){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"===typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:ca||"./this.program"},b;for(b in Yc)a[b]=Yc[b];var c=[];for(b in a)c.push(b+"="+a[b]);$c=c}return $c}var $c;function ad(a){return 0===a%4&&(0!==a%100||0===a%400)}function bd(a,b){for(var c=0,d=0;d<=b;c+=a[d++]);return c}
var cd=[31,29,31,30,31,30,31,31,30,31,30,31],dd=[31,28,31,30,31,30,31,31,30,31,30,31];function ed(a,b){for(a=new Date(a.getTime());0<b;){var c=a.getMonth(),d=(ad(a.getFullYear())?cd:dd)[c];if(b>d-a.getDate())b-=d-a.getDate()+1,a.setDate(1),11>c?a.setMonth(c+1):(a.setMonth(0),a.setFullYear(a.getFullYear()+1));else{a.setDate(a.getDate()+b);break}}return a}
function fd(a,b,c,d){function e(h,n,u){for(h="number"===typeof h?h.toString():h||"";h.length<n;)h=u[0]+h;return h}function g(h,n){return e(h,n,"0")}function k(h,n){function u(D){return 0>D?-1:0<D?1:0}var t;0===(t=u(h.getFullYear()-n.getFullYear()))&&0===(t=u(h.getMonth()-n.getMonth()))&&(t=u(h.getDate()-n.getDate()));return t}function l(h){switch(h.getDay()){case 0:return new Date(h.getFullYear()-1,11,29);case 1:return h;case 2:return new Date(h.getFullYear(),0,3);case 3:return new Date(h.getFullYear(),
0,2);case 4:return new Date(h.getFullYear(),0,1);case 5:return new Date(h.getFullYear()-1,11,31);case 6:return new Date(h.getFullYear()-1,11,30)}}function q(h){h=ed(new Date(h.pa+1900,0,1),h.Ua);var n=new Date(h.getFullYear()+1,0,4),u=l(new Date(h.getFullYear(),0,4));n=l(n);return 0>=k(u,h)?0>=k(n,h)?h.getFullYear()+1:h.getFullYear():h.getFullYear()-1}var m=F[d+40>>2];d={Mb:F[d>>2],Lb:F[d+4>>2],Sa:F[d+8>>2],Ja:F[d+12>>2],Ga:F[d+16>>2],pa:F[d+20>>2],Ta:F[d+24>>2],Ua:F[d+28>>2],Wb:F[d+32>>2],Kb:F[d+
36>>2],Nb:m?m?C(E,m,void 0):"":""};c=c?C(E,c,void 0):"";m={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S","%Ec":"%c","%EC":"%C","%Ex":"%m/%d/%y","%EX":"%H:%M:%S","%Ey":"%y","%EY":"%Y","%Od":"%d","%Oe":"%e","%OH":"%H","%OI":"%I","%Om":"%m","%OM":"%M","%OS":"%S","%Ou":"%u","%OU":"%U","%OV":"%V","%Ow":"%w","%OW":"%W","%Oy":"%y"};for(var r in m)c=c.replace(new RegExp(r,"g"),m[r]);var w="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),
x="January February March April May June July August September October November December".split(" ");m={"%a":function(h){return w[h.Ta].substring(0,3)},"%A":function(h){return w[h.Ta]},"%b":function(h){return x[h.Ga].substring(0,3)},"%B":function(h){return x[h.Ga]},"%C":function(h){return g((h.pa+1900)/100|0,2)},"%d":function(h){return g(h.Ja,2)},"%e":function(h){return e(h.Ja,2," ")},"%g":function(h){return q(h).toString().substring(2)},"%G":function(h){return q(h)},"%H":function(h){return g(h.Sa,
2)},"%I":function(h){h=h.Sa;0==h?h=12:12<h&&(h-=12);return g(h,2)},"%j":function(h){return g(h.Ja+bd(ad(h.pa+1900)?cd:dd,h.Ga-1),3)},"%m":function(h){return g(h.Ga+1,2)},"%M":function(h){return g(h.Lb,2)},"%n":function(){return"\n"},"%p":function(h){return 0<=h.Sa&&12>h.Sa?"AM":"PM"},"%S":function(h){return g(h.Mb,2)},"%t":function(){return"\t"},"%u":function(h){return h.Ta||7},"%U":function(h){var n=new Date(h.pa+1900,0,1),u=0===n.getDay()?n:ed(n,7-n.getDay());h=new Date(h.pa+1900,h.Ga,h.Ja);return 0>
k(u,h)?g(Math.ceil((31-u.getDate()+(bd(ad(h.getFullYear())?cd:dd,h.getMonth()-1)-31)+h.getDate())/7),2):0===k(u,n)?"01":"00"},"%V":function(h){var n=new Date(h.pa+1901,0,4),u=l(new Date(h.pa+1900,0,4));n=l(n);var t=ed(new Date(h.pa+1900,0,1),h.Ua);return 0>k(t,u)?"53":0>=k(n,t)?"01":g(Math.ceil((u.getFullYear()<h.pa+1900?h.Ua+32-u.getDate():h.Ua+1-u.getDate())/7),2)},"%w":function(h){return h.Ta},"%W":function(h){var n=new Date(h.pa,0,1),u=1===n.getDay()?n:ed(n,0===n.getDay()?1:7-n.getDay()+1);h=
new Date(h.pa+1900,h.Ga,h.Ja);return 0>k(u,h)?g(Math.ceil((31-u.getDate()+(bd(ad(h.getFullYear())?cd:dd,h.getMonth()-1)-31)+h.getDate())/7),2):0===k(u,n)?"01":"00"},"%y":function(h){return(h.pa+1900).toString().substring(2)},"%Y":function(h){return h.pa+1900},"%z":function(h){h=h.Kb;var n=0<=h;h=Math.abs(h)/60;return(n?"+":"-")+String("0000"+(h/60*100+h%60)).slice(-4)},"%Z":function(h){return h.Nb},"%%":function(){return"%"}};for(r in m)0<=c.indexOf(r)&&(c=c.replace(new RegExp(r,"g"),m[r](d)));r=
lb(c,!1);if(r.length>b)return 0;G.set(r,a);return r.length-1}function Eb(a,b,c,d){a||(a=this);this.parent=a;this.ya=a.ya;this.Qa=null;this.id=wb++;this.name=b;this.mode=c;this.ja={};this.ka={};this.rdev=d}Object.defineProperties(Eb.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}}});Sb();xb=Array(4096);Lb(M,"/");O("/tmp");O("/home");
O("/home/web_user");
(function(){O("/dev");jb(259,{read:function(){return 0},write:function(d,e,g,k){return k}});Nb("/dev/null",259);ib(1280,mb);ib(1536,nb);Nb("/dev/tty",1280);Nb("/dev/tty1",1536);if("object"===typeof crypto&&"function"===typeof crypto.getRandomValues){var a=new Uint8Array(1);var b=function(){crypto.getRandomValues(a);return a[0]}}else if(ea)try{var c=require("crypto");b=function(){return c.randomBytes(1)[0]}}catch(d){}b||(b=function(){z("random_device")});Vb("random",b);Vb("urandom",b);O("/dev/shm");
O("/dev/shm/tmp")})();O("/proc");O("/proc/self");O("/proc/self/fd");Lb({ya:function(){var a=pb("/proc/self","fd",16895,73);a.ja={lookup:function(b,c){var d=vb[+c];if(!d)throw new L(8);b={parent:null,ya:{lb:"fake"},ja:{readlink:function(){return d.path}}};return b.parent=b}};return a}},"/proc/self/fd");ic=f.InternalError=hc("InternalError");for(var gd=Array(256),hd=0;256>hd;++hd)gd[hd]=String.fromCharCode(hd);mc=gd;nc=f.BindingError=hc("BindingError");
T.prototype.isAliasOf=function(a){if(!(this instanceof T&&a instanceof T))return!1;var b=this.ha.oa.la,c=this.ha.ma,d=a.ha.oa.la;for(a=a.ha.ma;b.sa;)c=b.Ka(c),b=b.sa;for(;d.sa;)a=d.Ka(a),d=d.sa;return b===d&&c===a};T.prototype.clone=function(){this.ha.ma||pc(this);if(this.ha.Ia)return this.ha.count.value+=1,this;var a=tc(Object.create(Object.getPrototypeOf(this),{ha:{value:oc(this.ha)}}));a.ha.count.value+=1;a.ha.Da=!1;return a};
T.prototype["delete"]=function(){this.ha.ma||pc(this);this.ha.Da&&!this.ha.Ia&&S("Object already scheduled for deletion");rc(this);sc(this.ha);this.ha.Ia||(this.ha.qa=void 0,this.ha.ma=void 0)};T.prototype.isDeleted=function(){return!this.ha.ma};T.prototype.deleteLater=function(){this.ha.ma||pc(this);this.ha.Da&&!this.ha.Ia&&S("Object already scheduled for deletion");vc.push(this);1===vc.length&&uc&&uc(wc);this.ha.Da=!0;return this};U.prototype.ub=function(a){this.mb&&(a=this.mb(a));return a};
U.prototype.eb=function(a){this.za&&this.za(a)};U.prototype.argPackAdvance=8;U.prototype.readValueFromPointer=bc;U.prototype.deleteObject=function(a){if(null!==a)a["delete"]()};
U.prototype.fromWireType=function(a){function b(){return this.Oa?Mc(this.la.Ea,{oa:this.Bb,ma:c,ra:this,qa:a}):Mc(this.la.Ea,{oa:this,ma:a})}var c=this.ub(a);if(!c)return this.eb(a),null;var d=Lc(this.la,c);if(void 0!==d){if(0===d.ha.count.value)return d.ha.ma=c,d.ha.qa=a,d.clone();d=d.clone();this.eb(a);return d}d=this.la.tb(c);d=xc[d];if(!d)return b.call(this);d=this.Na?d.pb:d.pointerType;var e=Jc(c,this.la,d.la);return null===e?b.call(this):this.Oa?Mc(d.la.Ea,{oa:d,ma:e,ra:this,qa:a}):Mc(d.la.Ea,
{oa:d,ma:e})};f.getInheritedInstanceCount=function(){return Object.keys(Kc).length};f.getLiveInheritedInstances=function(){var a=[],b;for(b in Kc)Kc.hasOwnProperty(b)&&a.push(Kc[b]);return a};f.flushPendingDeletes=wc;f.setDelayFunction=function(a){uc=a;vc.length&&uc&&uc(wc)};Oc=f.UnboundTypeError=hc("UnboundTypeError");f.count_emval_handles=function(){for(var a=0,b=5;b<X.length;++b)void 0!==X[b]&&++a;return a};f.get_first_emval=function(){for(var a=5;a<X.length;++a)if(void 0!==X[a])return X[a];return null};
function lb(a,b){var c=Array(ua(a)+1);a=ta(a,c,0,c.length);b&&(c.length=a);return c}
var jd={c:function(a){return sb(a)},b:function(a){"uncaught_exception"in bb?bb.Ma++:bb.Ma=1;throw a;},y:function(){F[id()>>2]=63;return-1},x:function(a,b){try{if(-1===(a|0)||0===b)var c=-28;else{var d=Yb[a];if(d&&b===d.Sb){var e=vb[d.fd];if(d.Vb&2){var g=d.flags,k=d.offset,l=E.slice(a,a+b);e&&e.ka.Ra&&e.ka.Ra(e,l,k,b,g)}Yb[a]=null;d.nb&&W(d.Tb)}c=0}return c}catch(q){return"undefined"!==typeof Xb&&q instanceof L||z(q),-q.Ha}},m:function(a){var b=$b[a];delete $b[a];var c=b.Za,d=b.za,e=b.gb,g=e.map(function(k){return k.xb}).concat(e.map(function(k){return k.Hb}));
kc([a],g,function(k){var l={};e.forEach(function(q,m){var r=k[m],w=q.vb,x=q.wb,h=k[m+e.length],n=q.Gb,u=q.Ib;l[q.rb]={read:function(t){return r.fromWireType(w(x,t))},write:function(t,D){var A=[];n(u,t,h.toWireType(A,D));ac(A)}}});return[{name:b.name,fromWireType:function(q){var m={},r;for(r in l)m[r]=l[r].read(q);d(q);return m},toWireType:function(q,m){for(var r in l)if(!(r in m))throw new TypeError('Missing field:  "'+r+'"');var w=c();for(r in l)l[r].write(w,m[r]);null!==q&&q.push(d,w);return w},
argPackAdvance:8,readValueFromPointer:bc,ta:d}]})},E:function(a,b,c,d,e){var g=lc(c);b=R(b);Q(a,{name:b,fromWireType:function(k){return!!k},toWireType:function(k,l){return l?d:e},argPackAdvance:8,readValueFromPointer:function(k){if(1===c)var l=G;else if(2===c)l=ya;else if(4===c)l=F;else throw new TypeError("Unknown boolean type size: "+b);return this.fromWireType(l[k>>g])},ta:null})},i:function(a,b,c,d,e,g,k,l,q,m,r,w,x){r=R(r);g=V(e,g);l&&(l=V(k,l));m&&(m=V(q,m));x=V(w,x);var h=ec(r);Bc(h,function(){Rc("Cannot construct "+
r+" due to unbound types",[d])});kc([a,b,c],d?[d]:[],function(n){n=n[0];if(d){var u=n.la;var t=u.Ea}else t=T.prototype;n=fc(h,function(){if(Object.getPrototypeOf(this)!==D)throw new nc("Use 'new' to construct "+r);if(void 0===A.Ba)throw new nc(r+" has no accessible constructor");var Y=A.Ba[arguments.length];if(void 0===Y)throw new nc("Tried to invoke ctor of "+r+" with invalid number of parameters ("+arguments.length+") - expected ("+Object.keys(A.Ba).toString()+") parameters instead!");return Y.apply(this,
arguments)});var D=Object.create(t,{constructor:{value:n}});n.prototype=D;var A=new Cc(r,n,D,x,u,g,l,m);u=new U(r,A,!0,!1);t=new U(r+"*",A,!1,!1);var ja=new U(r+" const*",A,!1,!0);xc[a]={pointerType:t,pb:ja};Nc(h,n);return[u,t,ja]})},h:function(a,b,c,d,e,g){assert(0<b);var k=Sc(b,c);e=V(d,e);var l=[g],q=[];kc([],[a],function(m){m=m[0];var r="constructor "+m.name;void 0===m.la.Ba&&(m.la.Ba=[]);if(void 0!==m.la.Ba[b-1])throw new nc("Cannot register multiple constructors with identical number of parameters ("+
(b-1)+") for class '"+m.name+"'! Overload resolution is currently only performed using the parameter count, not actual type info!");m.la.Ba[b-1]=function(){Rc("Cannot construct "+m.name+" due to unbound types",k)};kc([],k,function(w){m.la.Ba[b-1]=function(){arguments.length!==b-1&&S(r+" called with "+arguments.length+" arguments, expected "+(b-1));q.length=0;l.length=b;for(var x=1;x<b;++x)l[x]=w[x].toWireType(q,arguments[x-1]);x=e.apply(null,l);ac(q);return w[0].fromWireType(x)};return[]});return[]})},
a:function(a,b,c,d,e,g,k,l){var q=Sc(c,d);b=R(b);g=V(e,g);kc([],[a],function(m){function r(){Rc("Cannot call "+w+" due to unbound types",q)}m=m[0];var w=m.name+"."+b;l&&m.la.Cb.push(b);var x=m.la.Ea,h=x[b];void 0===h||void 0===h.va&&h.className!==m.name&&h.La===c-2?(r.La=c-2,r.className=m.name,x[b]=r):(yc(x,b,w),x[b].va[c-2]=r);kc([],q,function(n){var u=w,t=m,D=g,A=n.length;2>A&&S("argTypes array size mismatch! Must at least get return value and 'this' types!");var ja=null!==n[1]&&null!==t,Y=!1;for(t=
1;t<n.length;++t)if(null!==n[t]&&void 0===n[t].ta){Y=!0;break}var zc="void"!==n[0].name,Z="",ka="";for(t=0;t<A-2;++t)Z+=(0!==t?", ":"")+"arg"+t,ka+=(0!==t?", ":"")+"arg"+t+"Wired";u="return function "+ec(u)+"("+Z+") {\nif (arguments.length !== "+(A-2)+") {\nthrowBindingError('function "+u+" called with ' + arguments.length + ' arguments, expected "+(A-2)+" args!');\n}\n";Y&&(u+="var destructors = [];\n");var Ac=Y?"destructors":"null";Z="throwBindingError invoker fn runDestructors retType classParam".split(" ");
D=[S,D,k,ac,n[0],n[1]];ja&&(u+="var thisWired = classParam.toWireType("+Ac+", this);\n");for(t=0;t<A-2;++t)u+="var arg"+t+"Wired = argType"+t+".toWireType("+Ac+", arg"+t+"); // "+n[t+2].name+"\n",Z.push("argType"+t),D.push(n[t+2]);ja&&(ka="thisWired"+(0<ka.length?", ":"")+ka);u+=(zc?"var rv = ":"")+"invoker(fn"+(0<ka.length?", ":"")+ka+");\n";if(Y)u+="runDestructors(destructors);\n";else for(t=ja?1:2;t<n.length;++t)A=1===t?"thisWired":"arg"+(t-2)+"Wired",null!==n[t].ta&&(u+=A+"_dtor("+A+"); // "+
n[t].name+"\n",Z.push(A+"_dtor"),D.push(n[t].ta));zc&&(u+="var ret = retType.fromWireType(rv);\nreturn ret;\n");Z.push(u+"}\n");n=Tc(Z).apply(null,D);void 0===x[b].va?(n.La=c-2,x[b]=n):x[b].va[c-2]=n;return[]});return[]})},D:function(a,b){b=R(b);Q(a,{name:b,fromWireType:function(c){var d=X[c].value;Vc(c);return d},toWireType:function(c,d){return Hc(d)},argPackAdvance:8,readValueFromPointer:bc,ta:null})},o:function(a,b,c){c=lc(c);b=R(b);Q(a,{name:b,fromWireType:function(d){return d},toWireType:function(d,
e){if("number"!==typeof e&&"boolean"!==typeof e)throw new TypeError('Cannot convert "'+Fc(e)+'" to '+this.name);return e},argPackAdvance:8,readValueFromPointer:Wc(b,c),ta:null})},f:function(a,b,c,d,e){function g(m){return m}b=R(b);-1===e&&(e=4294967295);var k=lc(c);if(0===d){var l=32-8*c;g=function(m){return m<<l>>>l}}var q=-1!=b.indexOf("unsigned");Q(a,{name:b,fromWireType:g,toWireType:function(m,r){if("number"!==typeof r&&"boolean"!==typeof r)throw new TypeError('Cannot convert "'+Fc(r)+'" to '+
this.name);if(r<d||r>e)throw new TypeError('Passing a number "'+Fc(r)+'" from JS side to C/C++ side to an argument of type "'+b+'", which is outside the valid range ['+d+", "+e+"]!");return q?r>>>0:r|0},argPackAdvance:8,readValueFromPointer:Xc(b,k,0!==d),ta:null})},e:function(a,b,c){function d(g){g>>=2;return new e(Ea,H[g+1],H[g])}var e=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array][b];c=R(c);Q(a,{name:c,fromWireType:d,argPackAdvance:8,readValueFromPointer:d},
{yb:!0})},p:function(a,b){b=R(b);var c="std::string"===b;Q(a,{name:b,fromWireType:function(d){var e=H[d>>2];if(c)for(var g=d+4,k=0;k<=e;++k){var l=d+4+k;if(0==E[l]||k==e){g=g?C(E,g,l-g):"";if(void 0===q)var q=g;else q+=String.fromCharCode(0),q+=g;g=l+1}}else{q=Array(e);for(k=0;k<e;++k)q[k]=String.fromCharCode(E[d+4+k]);q=q.join("")}W(d);return q},toWireType:function(d,e){e instanceof ArrayBuffer&&(e=new Uint8Array(e));var g="string"===typeof e;g||e instanceof Uint8Array||e instanceof Uint8ClampedArray||
e instanceof Int8Array||S("Cannot pass non-string to std::string");var k=(c&&g?function(){return ua(e)}:function(){return e.length})(),l=sb(4+k+1);H[l>>2]=k;if(c&&g)ta(e,E,l+4,k+1);else if(g)for(g=0;g<k;++g){var q=e.charCodeAt(g);255<q&&(W(l),S("String has UTF-16 code units that do not fit in 8 bits"));E[l+4+g]=q}else for(g=0;g<k;++g)E[l+4+g]=e[g];null!==d&&d.push(W,l);return l},argPackAdvance:8,readValueFromPointer:bc,ta:function(d){W(d)}})},j:function(a,b,c){c=R(c);if(2===b){var d=wa;var e=za;var g=
Aa;var k=function(){return xa};var l=1}else 4===b&&(d=Ba,e=Ca,g=Da,k=function(){return H},l=2);Q(a,{name:c,fromWireType:function(q){for(var m=H[q>>2],r=k(),w,x=q+4,h=0;h<=m;++h){var n=q+4+h*b;if(0==r[n>>l]||h==m)x=d(x,n-x),void 0===w?w=x:(w+=String.fromCharCode(0),w+=x),x=n+b}W(q);return w},toWireType:function(q,m){"string"!==typeof m&&S("Cannot pass non-string to C++ string type "+c);var r=g(m),w=sb(4+r+b);H[w>>2]=r>>l;e(m,w+4,r+b);null!==q&&q.push(W,w);return w},argPackAdvance:8,readValueFromPointer:bc,
ta:function(q){W(q)}})},r:function(a,b,c,d,e,g){$b[a]={name:R(b),Za:V(c,d),za:V(e,g),gb:[]}},d:function(a,b,c,d,e,g,k,l,q,m){$b[a].gb.push({rb:R(b),xb:c,vb:V(d,e),wb:g,Hb:k,Gb:V(l,q),Ib:m})},F:function(a,b){b=R(b);Q(a,{Rb:!0,name:b,argPackAdvance:0,fromWireType:function(){},toWireType:function(){}})},q:Vc,k:function(a){4<a&&(X[a].ab+=1)},g:function(a,b){var c=P[a];void 0===c&&S("_emval_take_value has unknown type "+Pc(a));a=c.readValueFromPointer(b);return Hc(a)},n:function(){z()},u:function(a,b,
c){E.copyWithin(a,b,b+c)},v:function(){z("OOM")},z:function(a,b){var c=0;Zc().forEach(function(d,e){var g=b+c;e=F[a+4*e>>2]=g;for(g=0;g<d.length;++g)G[e++>>0]=d.charCodeAt(g);G[e>>0]=0;c+=d.length+1});return 0},A:function(a,b){var c=Zc();F[a>>2]=c.length;var d=0;c.forEach(function(e){d+=e.length+1});F[b>>2]=d;return 0},C:function(a){try{var b=Zb(a);if(null===b.fd)throw new L(8);b.Wa&&(b.Wa=null);try{b.ka.close&&b.ka.close(b)}catch(c){throw c;}finally{vb[b.fd]=null}b.fd=null;return 0}catch(c){return"undefined"!==
typeof Xb&&c instanceof L||z(c),c.Ha}},B:function(a,b,c,d){try{a:{for(var e=Zb(a),g=a=0;g<c;g++){var k=F[b+(8*g+4)>>2],l=e,q=F[b+8*g>>2],m=k,r=void 0;if(0>m||0>r)throw new L(28);if(null===l.fd)throw new L(8);if(1===(l.flags&2097155))throw new L(8);if(16384===(l.node.mode&61440))throw new L(31);if(!l.ka.read)throw new L(28);var w="undefined"!==typeof r;if(!w)r=l.position;else if(!l.seekable)throw new L(70);var x=l.ka.read(l,G,q,m,r);w||(l.position+=x);var h=x;if(0>h){var n=-1;break a}a+=h;if(h<k)break}n=
a}F[d>>2]=n;return 0}catch(u){return"undefined"!==typeof Xb&&u instanceof L||z(u),u.Ha}},s:function(a,b,c,d,e){try{var g=Zb(a);a=4294967296*c+(b>>>0);if(-9007199254740992>=a||9007199254740992<=a)return-61;Rb(g,a,d);$a=[g.position>>>0,(Za=g.position,1<=+Oa(Za)?0<Za?(Ra(+Qa(Za/4294967296),4294967295)|0)>>>0:~~+Pa((Za-+(~~Za>>>0))/4294967296)>>>0:0)];F[e>>2]=$a[0];F[e+4>>2]=$a[1];g.Wa&&0===a&&0===d&&(g.Wa=null);return 0}catch(k){return"undefined"!==typeof Xb&&k instanceof L||z(k),k.Ha}},l:function(a,
b,c,d){try{a:{for(var e=Zb(a),g=a=0;g<c;g++){var k=e,l=F[b+8*g>>2],q=F[b+(8*g+4)>>2],m=void 0;if(0>q||0>m)throw new L(28);if(null===k.fd)throw new L(8);if(0===(k.flags&2097155))throw new L(8);if(16384===(k.node.mode&61440))throw new L(31);if(!k.ka.write)throw new L(28);k.seekable&&k.flags&1024&&Rb(k,0,2);var r="undefined"!==typeof m;if(!r)m=k.position;else if(!k.seekable)throw new L(70);var w=k.ka.write(k,G,l,q,m,void 0);r||(k.position+=w);try{if(k.path&&zb.onWriteToFile)zb.onWriteToFile(k.path)}catch(n){B("FS.trackingDelegate['onWriteToFile']('"+
k.path+"') threw an exception: "+n.message)}var x=w;if(0>x){var h=-1;break a}a+=x}h=a}F[d>>2]=h;return 0}catch(n){return"undefined"!==typeof Xb&&n instanceof L||z(n),n.Ha}},memory:pa,t:function(){},w:function(a,b,c,d){return fd(a,b,c,d)},table:qa};
(function(){function a(e){f.asm=e.exports;J--;f.monitorRunDependencies&&f.monitorRunDependencies(J);0==J&&(null!==Sa&&(clearInterval(Sa),Sa=null),Ta&&(e=Ta,Ta=null,e()))}function b(e){a(e.instance)}function c(e){return Ya().then(function(g){return WebAssembly.instantiate(g,d)}).then(e,function(g){B("failed to asynchronously prepare wasm: "+g);z(g)})}var d={a:jd};J++;f.monitorRunDependencies&&f.monitorRunDependencies(J);if(f.instantiateWasm)try{return f.instantiateWasm(d,a)}catch(e){return B("Module.instantiateWasm callback failed with error: "+
e),!1}(function(){if(oa||"function"!==typeof WebAssembly.instantiateStreaming||Va()||Ua("file://")||"function"!==typeof fetch)return c(b);fetch(K,{credentials:"same-origin"}).then(function(e){return WebAssembly.instantiateStreaming(e,d).then(b,function(g){B("wasm streaming compile failed: "+g);B("falling back to ArrayBuffer instantiation");return c(b)})})})();return{}})();
var ab=f.___wasm_call_ctors=function(){return(ab=f.___wasm_call_ctors=f.asm.G).apply(null,arguments)},sb=f._malloc=function(){return(sb=f._malloc=f.asm.H).apply(null,arguments)},Qc=f.___getTypeName=function(){return(Qc=f.___getTypeName=f.asm.I).apply(null,arguments)};f.___embind_register_native_and_builtin_types=function(){return(f.___embind_register_native_and_builtin_types=f.asm.J).apply(null,arguments)};
var id=f.___errno_location=function(){return(id=f.___errno_location=f.asm.K).apply(null,arguments)},W=f._free=function(){return(W=f._free=f.asm.L).apply(null,arguments)};f.dynCall_i=function(){return(f.dynCall_i=f.asm.M).apply(null,arguments)};f.dynCall_vi=function(){return(f.dynCall_vi=f.asm.N).apply(null,arguments)};f.dynCall_iii=function(){return(f.dynCall_iii=f.asm.O).apply(null,arguments)};f.dynCall_viii=function(){return(f.dynCall_viii=f.asm.P).apply(null,arguments)};
f.dynCall_ii=function(){return(f.dynCall_ii=f.asm.Q).apply(null,arguments)};f.dynCall_iiii=function(){return(f.dynCall_iiii=f.asm.R).apply(null,arguments)};f.dynCall_iiiii=function(){return(f.dynCall_iiiii=f.asm.S).apply(null,arguments)};f.dynCall_vii=function(){return(f.dynCall_vii=f.asm.T).apply(null,arguments)};f.dynCall_viiii=function(){return(f.dynCall_viiii=f.asm.U).apply(null,arguments)};f.dynCall_viiiii=function(){return(f.dynCall_viiiii=f.asm.V).apply(null,arguments)};
f.dynCall_iiiiii=function(){return(f.dynCall_iiiiii=f.asm.W).apply(null,arguments)};f.dynCall_viijii=function(){return(f.dynCall_viijii=f.asm.X).apply(null,arguments)};f.dynCall_jiji=function(){return(f.dynCall_jiji=f.asm.Y).apply(null,arguments)};f.dynCall_iidiiii=function(){return(f.dynCall_iidiiii=f.asm.Z).apply(null,arguments)};f.dynCall_iiiiiiiii=function(){return(f.dynCall_iiiiiiiii=f.asm._).apply(null,arguments)};f.dynCall_iiiiiii=function(){return(f.dynCall_iiiiiii=f.asm.$).apply(null,arguments)};
f.dynCall_iiiiij=function(){return(f.dynCall_iiiiij=f.asm.aa).apply(null,arguments)};f.dynCall_iiiiid=function(){return(f.dynCall_iiiiid=f.asm.ba).apply(null,arguments)};f.dynCall_iiiiijj=function(){return(f.dynCall_iiiiijj=f.asm.ca).apply(null,arguments)};f.dynCall_iiiiiiii=function(){return(f.dynCall_iiiiiiii=f.asm.da).apply(null,arguments)};f.dynCall_iiiiiijj=function(){return(f.dynCall_iiiiiijj=f.asm.ea).apply(null,arguments)};
f.dynCall_viiiiii=function(){return(f.dynCall_viiiiii=f.asm.fa).apply(null,arguments)};f.dynCall_v=function(){return(f.dynCall_v=f.asm.ga).apply(null,arguments)};var kd;Ta=function ld(){kd||md();kd||(Ta=ld)};
function md(){function a(){if(!kd&&(kd=!0,f.calledRun=!0,!ra)){f.noFSInit||Tb||(Tb=!0,Sb(),f.stdin=f.stdin,f.stdout=f.stdout,f.stderr=f.stderr,f.stdin?Vb("stdin",f.stdin):Ob("/dev/tty","/dev/stdin"),f.stdout?Vb("stdout",null,f.stdout):Ob("/dev/tty","/dev/stdout"),f.stderr?Vb("stderr",null,f.stderr):Ob("/dev/tty1","/dev/stderr"),Pb("/dev/stdin","r"),Pb("/dev/stdout","w"),Pb("/dev/stderr","w"));Ia(Ka);yb=!1;Ia(La);aa(f);if(f.onRuntimeInitialized)f.onRuntimeInitialized();if(f.postRun)for("function"==
typeof f.postRun&&(f.postRun=[f.postRun]);f.postRun.length;){var b=f.postRun.shift();Ma.unshift(b)}Ia(Ma)}}if(!(0<J)){if(f.preRun)for("function"==typeof f.preRun&&(f.preRun=[f.preRun]);f.preRun.length;)Na();Ia(Ja);0<J||(f.setStatus?(f.setStatus("Running..."),setTimeout(function(){setTimeout(function(){f.setStatus("")},1);a()},1)):a())}}f.run=md;if(f.preInit)for("function"==typeof f.preInit&&(f.preInit=[f.preInit]);0<f.preInit.length;)f.preInit.pop()();noExitRuntime=!0;md();


  return Module.ready
}
);
})();
if (typeof exports === 'object' && typeof module === 'object')
      module.exports = Module;
    else if (typeof define === 'function' && define['amd'])
      define([], function() { return Module; });
    else if (typeof exports === 'object')
      exports["Module"] = Module;
    